export const words = {
  2362720225: {
    sortId: "1",
    tc: "屋企",
    yueYin: "uk1 kei2",
    cn: "",
    pinyin: "wū qǐ",
    mandarin: "家",
    category: "명사",
    title: "집",
    mean: "집/가족",
  },
  38646: {
    sortId: "0",
    tc: "零",
    yueYin: "ling4",
    cn: "",
    pinyin: "líng",
    mandarin: "",
    hanja: "떨어질 령(영) / 영 령(영)",
    category: "숫자",
    title: "숫자 0",
    mean: "숫자 0(영)/적은 수량/떨어지다",
  },
};
