export const wordData = {
  2017026085: {
    mean: "오늘/지금의 시대",
    category: "일자, 명사",
    tc: "今日",
    mandarin: "今天",
    title: "금일 (오늘)",
    yueYin: "gam1 jat6",
    pinyin: "jīn rì",
    sortId: "1",
  },
  2032022909: {
    category: "인사말",
    title: "안녕하세요",
    detail: "한국의 존댓말에 비교하면 반말이 아니다. [안녕]과 [안녕하세요]의 사이이다.",
    mandarin: "",
    sortId: "9",
    mean: "안녕하세요",
    pinyin: "nǐ hǎo",
    cn: "",
    tc: "你好",
    yueYin: "nei5 hou2",
  },
  2057226085: {
    relevance: "聽日 停日",
    sortId: "8",
    tc: "停日",
    cn: "",
    mean: "내일; 오늘의 하루 다음 날",
    mandarin: "明天",
    category: "일자, 명사",
    yueYin: "ting4 jat6",
    pinyin: "tíng rì",
    title: "내일",
    detail:
      "[ 聽日 ]을 제일 많이 사용하고 [ 停日 ]을 사용하는 사람도 있다. 소수의 사람들은 [ 天日 ]이라고  쓴다. 유래에 대해서는 여러 추측이 있다. [ 天光日 ] 혹 [ 天明日 ]의 줄임말일 가능성이 있다. 후난어 (湖南話)의 [ 等日 ]에서 유래했다는 추측도 있다. 하지만 명확한 기록이 없어서 그냥 추측일 뿐이다.",
  },
  2087735211: {
    pinyin: "zài jiàn",
    mean: "해어질 때 인사말. 또 다시 만나요",
    detail: "[안녕히계세요], [안녕히가세요]같은 인사말로 사용된다. 가끔 다시 만날 기회가 별로 없어서 '기회가 된다면 다시 보자'는 뜻으로도 사용된다",
    cn: "再见",
    yueYin: "zoi3 gin3",
    tc: "再見",
    sortId: "11",
    category: "인사말",
    title: "또 만나요",
    mandarin: "",
  },
  2210626085: {
    sortId: "3",
    mean: "어제; 오늘의 하루 전날",
    mandarin: "昨天",
    relevance: "噚日 尋日 擒日 琴日",
    pinyin: "xún rì",
    detail:
      '[ 噚日 尋日 擒日 琴日 ] 4개를 사용한다. [ 尋日 cam4 jat6 ]이 문서로 제일 많이 사용되고, 대화에 서는 [ 擒日 琴日 kam4 jat6 ]도 많이 사용된다. 원래의 뜻은 "어제 낮"이었지만, 지금은 "어제" 전체를 뜻하는 단 어이다. [ 昨冥日 ]에서 앞 두 글자를 합성해서 만들어진 단어이다. ',
    tc: "噚日",
    yueYin: "cam4 jat6",
    category: "일자, 명사",
    cn: "寻日",
    title: "어제",
  },
  2356326085: {
    detail:
      '[ 噚日 尋日 擒日 琴日 ] 4개를 사용한다. [ 尋日 cam4 jat6 ]이 문서로 제일 많이 사용되고, 대화에 서는 [ 擒日 琴日 kam4 jat6 ]도 많이 사용된다. 원래의 뜻은 "어제 낮"이었지만, 지금은 "어제" 전체를 뜻하는 단 어이다. [ 昨冥日 ]에서 앞 두 글자를 합성해서 만들어진 단어이다. ',
    pinyin: "xún rì",
    title: "어제",
    tc: "尋日",
    sortId: "2",
    cn: "寻日",
    mandarin: "昨天",
    mean: "어제; 오늘의 하루 전날",
    relevance: "噚日 尋日 擒日 琴日",
    yueYin: "cam4 jat6",
    category: "일자, 명사",
  },
  2362720225: {
    pinyin: "wū qǐ",
    mandarin: "家",
    sortId: "0",
    title: "집",
    category: "명사",
    yueYin: "uk1 kei2",
    cn: "",
    mean: "집/가족",
    tc: "屋企",
  },
  2474422909: {
    mean: "안녕하십니까",
    yueYin: "nei5 hou2",
    mandarin: "",
    detail: "비즈니스와 고객에게만 사용되는 말이다.",
    category: "인사말",
    cn: "",
    title: "안녕하십니까",
    tc: "您好",
    pinyin: "nín hǎo",
    sortId: "10",
  },
  2530825308: {
    mandarin: "",
    title: "Bye Bye. 제사",
    cn: "",
    tc: "拜拜",
    detail:
      "[掰掰], [拜拜] 둘 다 사용된다. [拜拜]는 2가지 뜻이 있어서 [掰掰]를 사용하자는 사람이 많다. 하지만 둘 다 음역이고, 홍콩에서는 그냥 [Bye Bye]라고 많이 한다. [baai4]로 발음하는 사람도 많다. (baai4는 광둥어 에 존재하지 않는 음이다)",
    yueYin: "baai1 baai1",
    sortId: "13",
    pinyin: "bài bài",
    category: "인사말 동사",
    mean: "해어질 때 인사말 영어 Bye Bye의 음역/제사. 신이나 고인을 섬기는 의식을 하다/절하다",
  },
  2552025520: {
    mandarin: "拜拜",
    sortId: "12",
    cn: "",
    title: "Bye Bye",
    category: "인사말",
    tc: "掰掰",
    detail:
      "[掰掰], [拜拜] 둘 다 사용된다. [拜拜]는 2가지 뜻이 있어서 [掰掰]를 사용하자는 사람이 많다. 하지만 둘 다 음역이고, 홍콩에서는 그냥 [Bye Bye]라고 많이 한다. [baai4]로 발음하는 사람도 많다. (baai4는 광둥어 에 존재하지 않는 음이다)",
    yueYin: "baai1 baai1",
    pinyin: "bāi bāi",
    mean: "해어질 때 인사말 영어 Bye Bye의 음역.",
  },
  2581026085: {
    relevance: "噚日 尋日 擒日 琴日",
    sortId: "4",
    mean: "어제; 오늘의 하루 전날",
    yueYin: "kam4 jat6",
    category: "일자, 명사",
    cn: "",
    title: "어제",
    mandarin: "昨天",
    pinyin: "qín rì",
    tc: "擒日",
    detail:
      '[ 噚日 尋日 擒日 琴日 ] 4개를 사용한다. [ 尋日 cam4 jat6 ]이 문서로 제일 많이 사용되고, 대화에 서는 [ 擒日 琴日 kam4 jat6 ]도 많이 사용된다. 원래의 뜻은 "어제 낮"이었지만, 지금은 "어제" 전체를 뜻하는 단 어이다. [ 昨冥日 ]에서 앞 두 글자를 합성해서 만들어진 단어이다. ',
  },
  2974826085: {
    tc: "琴日",
    cn: "",
    category: "일자, 명사",
    mandarin: "昨天",
    relevance: "噚日 尋日 擒日 琴日",
    pinyin: "qín rì",
    yueYin: "kam4 jat6",
    title: "어제",
    detail:
      '[ 噚日 尋日 擒日 琴日 ] 4개를 사용한다. [ 尋日 cam4 jat6 ]이 문서로 제일 많이 사용되고, 대화에 서는 [ 擒日 琴日 kam4 jat6 ]도 많이 사용된다. 원래의 뜻은 "어제 낮"이었지만, 지금은 "어제" 전체를 뜻하는 단 어이다. [ 昨冥日 ]에서 앞 두 글자를 합성해서 만들어진 단어이다. ',
    mean: "어제; 오늘의 하루 전날",
    sortId: "5",
  },
  3116526085: {
    title: "어제",
    tc: "禽日",
    cn: "",
    category: "일자, 명사",
    mandarin: "昨天",
    relevance: "噚日 尋日 擒日 琴日",
    mean: "어제 [ 擒日 ]의 민간에서 줄여 쓴 단어",
    sortId: "6",
    yueYin: "kam4 jat6",
    pinyin: "qín rì",
    detail: "",
  },
  3289326085: {
    relevance: "聽日 停日",
    pinyin: "tīng rì",
    tc: "聽日",
    detail:
      "[ 聽日 ]을 제일 많이 사용하고 [ 停日 ]을 사용하는 사람도 있다. 소수의 사람들은 [ 天日 ]이라고  쓴다. 유래에 대해서는 여러 추측이 있다. [ 天光日 ] 혹 [ 天明日 ]의 줄임말일 가능성이 있다. 후난어 (湖南話)의 [ 等日 ]에서 유래했다는 추측도 있다. 하지만 명확한 기록이 없어서 그냥 추측일 뿐이다.",
    mean: "내일; 오늘의 하루 다음 날",
    sortId: "7",
    yueYin: "ting1 jat6",
    cn: "听日",
    category: "일자, 명사",
    title: "내일",
    mandarin: "明天",
  },
};
