export const wordData = {
  2017026085: {
    mean: "오늘/지금의 시대",
    category: "일자, 명사",
    tc: "今日",
    mandarin: "今天",
    title: "금일 (오늘)",
    yueYin: "gam1 jat6",
    pinyin: "jīn rì",
    sortId: "1",
    meaning: [{ m: "오늘" }, { e: "今日要去大埔見個客", t: "오늘 타이포에서 손님을 만나야 한다" }, { m: "지금의 시대" }, { e: "今時今日咁嘅服務態度唔夠架", t: "현시대에서 이러한 서비스 품질을 충분하지 않다 (홍콩 공익광고 대사)" }],
  },
  2032022909: {
    category: "인사말",
    title: "안녕하세요",
    detail: "한국의 존댓말에 비교하면 반말이 아니다. [안녕]과 [안녕하세요]의 사이이다.",
    mandarin: "",
    sortId: "9",
    mean: "안녕하세요",
    meaning: [{ m: "안녕하세요" }],
    pinyin: "nǐ hǎo",
    cn: "",
    tc: "你好",
    yueYin: "nei5 hou2",
  },
  2057226085: {
    relevance: "聽日 停日",
    sortId: "8",
    tc: "停日",
    cn: "",
    mean: "내일; 오늘의 하루 다음 날",
    meaning: [{ m: "내일; 오늘의 하루 다음 날" }, { e: "停日仲要返學，早啲瞓喇", t: "내일 학교가야 하니 빨리 자라" }],
    mandarin: "明天",
    category: "일자, 명사",
    yueYin: "ting4 jat6",
    pinyin: "tíng rì",
    title: "내일",
    detail: "[ 聽日 ]을 제일 많이 사용하고 [ 停日 ]을 사용하는 사람도 있다. 소수의 사람들은 [ 天日 ]이라고  쓴다. 유래에 대해서는 여러 추측이 있다. [ 天光日 ] 혹 [ 天明日 ]의 줄임말일 가능성이 있다. 후난어 (湖南話)의 [ 等日 ]에서 유래했다는 추측도 있다. 하지만 명확한 기록이 없어서 그냥 추측일 뿐이다.",
  },
  2087735211: {
    pinyin: "zài jiàn",
    mean: "해어질 때 인사말. 또 다시 만나요",
    meaning: [{ m: "해어질 때 인사말. 또 다시 만나요" }],
    detail: "[안녕히계세요], [안녕히가세요]같은 인사말로 사용된다. 가끔 다시 만날 기회가 별로 없어서 '기회가 된다면 다시 보자'는 뜻으로도 사용된다",
    cn: "再见",
    yueYin: "zoi3 gin3",
    tc: "再見",
    sortId: "11",
    category: "인사말",
    title: "또 만나요",
    mandarin: "",
  },
  2210626085: {
    sortId: "3",
    mean: "어제; 오늘의 하루 전날",
    meaning: [{ m: "어제; 오늘의 하루 전날" }, { e: "噚日打完波，今日周身痛", t: "어제 운동을 해서 오늘 온몸이 아프다" }],
    mandarin: "昨天",
    relevance: "噚日 尋日 擒日 琴日",
    pinyin: "xún rì",
    detail: '[ 噚日 尋日 擒日 琴日 ] 4개를 사용한다. [ 尋日 cam4 jat6 ]이 문서로 제일 많이 사용되고, 대화에 서는 [ 擒日 琴日 kam4 jat6 ]도 많이 사용된다. 원래의 뜻은 "어제 낮"이었지만, 지금은 "어제" 전체를 뜻하는 단 어이다. [ 昨冥日 ]에서 앞 두 글자를 합성해서 만들어진 단어이다. ',
    tc: "噚日",
    yueYin: "cam4 jat6",
    category: "일자, 명사",
    cn: "寻日",
    title: "어제",
  },
  2356326085: {
    detail: '[ 噚日 尋日 擒日 琴日 ] 4개를 사용한다. [ 尋日 cam4 jat6 ]이 문서로 제일 많이 사용되고, 대화에 서는 [ 擒日 琴日 kam4 jat6 ]도 많이 사용된다. 원래의 뜻은 "어제 낮"이었지만, 지금은 "어제" 전체를 뜻하는 단 어이다. [ 昨冥日 ]에서 앞 두 글자를 합성해서 만들어진 단어이다. ',
    pinyin: "xún rì",
    title: "어제",
    tc: "尋日",
    sortId: "2",
    cn: "寻日",
    mandarin: "昨天",
    mean: "어제",
    meaning: [{ m: "어제; 오늘의 하루 전날" }, { e: "尋日打完波，今日周身痛", t: "어제 운동을 해서 오늘 온몸이 아프다" }],
    relevance: "噚日 尋日 擒日 琴日",
    yueYin: "cam4 jat6",
    category: "일자, 명사",
  },
  2362720225: {
    pinyin: "wū qǐ",
    mandarin: "家",
    sortId: "0",
    title: "집",
    meaning: [{ m: "집/가족" }, { e: "佢出咗去，夜晚先返屋企", t: "그는 나갔다. 밤이 되어야 집에 돌아온다" }],
    category: "명사",
    yueYin: "uk1 kei2",
    cn: "",
    mean: "집/가족",
    tc: "屋企",
  },
  2474422909: {
    mean: "안녕하십니까",
    meaning: [{ m: "안녕하십니까" }],
    yueYin: "nei5 hou2",
    mandarin: "",
    detail: "비즈니스와 고객에게만 사용되는 말이다.",
    category: "인사말",
    cn: "",
    title: "안녕하십니까",
    tc: "您好",
    pinyin: "nín hǎo",
    sortId: "10",
  },
  2530825308: {
    mandarin: "",
    title: "Bye Bye. 제사",
    cn: "",
    tc: "拜拜",
    detail: '[掰掰], [拜拜] 둘 다 사용된다.\n[拜拜]는 2가지 뜻이 있어서 [掰掰]를 사용하자는 사람이 많다.\n하지만 둘 다 음역이고, [掰]도 "벌리다. 부러트리다"는 뜻이 있다.\n홍콩에서는 그냥 [Bye Bye]라고 많이 한다. [baai4]로 발음하는 사람도 많다. (baai4는 광둥어에 없는 음이다)',
    yueYin: "baai1 baai1",
    sortId: "13",
    pinyin: "bài bài",
    category: "인사말 동사",
    mean: "해어질 때 인사말 영어 Bye Bye의 음역/제사. 신이나 고인을 섬기는 의식을 하다/절하다",
    meaning: [{ m: "해어질 때 인사말 영어 Bye Bye의 음역" }, { m: "제사. 신이나 고인을 섬기는 의식을 하다" }, { e: "拜佛", t: "불(佛)에 기도하다. 소원을 빌다." }, { m: "절하다, 섬기다" }, { e: "三拜九叩", t: "왕이나 선조에 절하는 정식 자세" }, { e: "拜師", t: "선생님으로 모시다" }],
  },
  2552025520: {
    mandarin: "拜拜",
    sortId: "12",
    cn: "",
    title: "Bye Bye",
    meaning: [{ m: "해어질 때 인사말 영어 Bye Bye의 음역." }],
    category: "인사말",
    tc: "掰掰",
    detail: '[掰掰], [拜拜] 둘 다 사용된다.\n[拜拜]는 2가지 뜻이 있어서 [掰掰]를 사용하자는 사람이 많다.\n하지만 둘 다 음역이고, [掰]도 "벌리다. 부러트리다"는 뜻이 있다.\n홍콩에서는 그냥 [Bye Bye]라고 많이 한다. [baai4]로 발음하는 사람도 많다. (baai4는 광둥어에 없는 음이다)',
    yueYin: "baai1 baai1",
    pinyin: "bāi bāi",
    mean: "해어질 때 인사말 영어 Bye Bye의 음역.",
  },
  2581026085: {
    relevance: "噚日 尋日 擒日 琴日",
    sortId: "4",
    mean: "어제; 오늘의 하루 전날",
    yueYin: "kam4 jat6",
    category: "일자, 명사",
    meaning: [{ m: "어제; 오늘의 하루 전날" }, { e: "擒日打完波，今日周身痛", t: "어제 운동을 해서 오늘 온몸이 아프다" }],
    cn: "",
    title: "어제",
    mandarin: "昨天",
    pinyin: "qín rì",
    tc: "擒日",
    detail: '[ 噚日 尋日 擒日 琴日 ] 4개를 사용한다. [ 尋日 cam4 jat6 ]이 문서로 제일 많이 사용되고, 대화에 서는 [ 擒日 琴日 kam4 jat6 ]도 많이 사용된다. 원래의 뜻은 "어제 낮"이었지만, 지금은 "어제" 전체를 뜻하는 단 어이다. [ 昨冥日 ]에서 앞 두 글자를 합성해서 만들어진 단어이다. ',
  },
  2974826085: {
    tc: "琴日",
    cn: "",
    category: "일자, 명사",
    mandarin: "昨天",
    relevance: "噚日 尋日 擒日 琴日",
    pinyin: "qín rì",
    yueYin: "kam4 jat6",
    title: "어제",
    meaning: [{ m: "어제; 오늘의 하루 전날" }, { e: "琴日打完波，今日周身痛", t: "어제 운동을 해서 오늘 온몸이 아프다" }],
    detail: '[ 噚日 尋日 擒日 琴日 ] 4개를 사용한다. [ 尋日 cam4 jat6 ]이 문서로 제일 많이 사용되고, 대화에 서는 [ 擒日 琴日 kam4 jat6 ]도 많이 사용된다. 원래의 뜻은 "어제 낮"이었지만, 지금은 "어제" 전체를 뜻하는 단 어이다. [ 昨冥日 ]에서 앞 두 글자를 합성해서 만들어진 단어이다. ',
    mean: "어제; 오늘의 하루 전날",
    sortId: "5",
  },
  3116526085: {
    title: "어제",
    tc: "禽日",
    cn: "",
    category: "일자, 명사",
    mandarin: "昨天",
    relevance: "噚日 尋日 擒日 琴日",
    mean: "어제 [ 擒日 ]의 민간에서 줄여 쓴 단어",
    meaning: [{ m: "어제 [ 擒日 ]의 민간에서 (횟수)줄여 쓴 단어" }, { e: "禽日打完波，今日周身痛", t: "어제 운동을 해서 오늘 온몸이 아프다" }],
    sortId: "6",
    yueYin: "kam4 jat6",
    pinyin: "qín rì",
    detail: "",
  },
  3289326085: {
    relevance: "聽日 停日",
    pinyin: "tīng rì",
    tc: "聽日",
    meaning: [{ m: "내일; 오늘의 하루 다음 날" }, { e: "聽日仲要返學，早啲瞓喇", t: "내일 학교가야 하니 빨리 자라" }],
    detail: "[ 聽日 ]을 제일 많이 사용하고 [ 停日 ]을 사용하는 사람도 있다. 소수의 사람들은 [ 天日 ]이라고  쓴다. 유래에 대해서는 여러 추측이 있다. [ 天光日 ] 혹 [ 天明日 ]의 줄임말일 가능성이 있다. 후난어 (湖南話)의 [ 等日 ]에서 유래했다는 추측도 있다. 하지만 명확한 기록이 없어서 그냥 추측일 뿐이다.",
    mean: "내일; 오늘의 하루 다음 날",
    sortId: "7",
    yueYin: "ting1 jat6",
    cn: "听日",
    category: "일자, 명사",
    title: "내일",
    mandarin: "明天",
  },
  201543895739151: {
    sortId: "14",
    tc: "人頭飯",
    yueYin: "jan4 tau4 faan4",
    cn: "人头饭",
    pinyin: "rén tóu fàn",
    mandarin: "一人一个饭",
    category: "명사",
    meaning: [{ m: "인원수 만큼의 공기밥" }, { e: "唔該要人頭飯", t: "한 사람당 공기밥 1개 주세요" }],
    mean: "인원수 만큼의 공기밥",
    title: "사람 수 공기밥",
  },
  288183979939770: {
    sortId: "15",
    tc: "炒魷魚",
    yueYin: "caau2 jau4 jyu2",
    cn: "炒鱿鱼",
    pinyin: "chǎo yóu yú",
    mandarin: "解雇",
    category: "동사",
    title: "해고",
    meaning: [{ m: "해고하다" }, { e: "被人炒魷魚", t: "회사에서 짤렸다" }, { e: "炒老闆魷魚", t: "퇴사하다 (대표/사장을 짜르다)" }],
    mean: "해고 해고하다 짤리다",
  },
  2178035442: {
    sortId: "16",
    tc: "唔該",
    yueYin: "m4 goi1",
    cn: "唔该",
    pinyin: "wú gāi",
    mandarin: "不好意思麻烦你",
    category: "구절",
    title: "실례합니다/감사합니다",
    meaning: [
      { m: "직역 : 신경 쓰게 하면 안 되는데" },
      { m: "(신경 써주셔서) 감사합니다. 보통 예상 내의 호의를 받았을 때" },
      { e: "唔該晒你", t: "감사합니다" },
      { m: "저기요. 실례합니다. 예의 있게 타인이 자신을 의식하도록 할 때" },
      { e: "唔該，請問地鐵站喺邊啊？", t: "실례합니다. 지하철역은 어디에 있나요?" },
      { m: "~ 부탁합니다. 자신의 요구를 예의있게 얘기할 때 (무례한 요구에 사용 시, 짜증났다는 표현이 된다)" },
      { e: "唔該我要杯美式啊", t: "아메리카노 한잔 주세요" },
      { e: "唔該你收嗲", t: "좀 닥쳐주세요" },
    ],
    mean: "신경 쓰게 하면 안 되는데 / 감사합니다 / 저기요. 실례합니다 / ~ 부탁합니다",
  },
  4067035299: {
    sortId: "17",
    tc: "點解",
    yueYin: "dim2 gaai2",
    cn: "点解",
    pinyin: "diǎn jiě",
    mandarin: "为什么 怎么解",
    category: "대명사 의문대명사",
    title: "왜",
    meaning: [{ m: "직역 : 어떻게 해석/풀 것인가?" }, { m: "왜" }, { e: "佢點解冇嚟？", t: "그는 왜 안 왔는가?" }],
    mean: "왜 / 어떻게 해석하나 / 어떻게 풀 것인가",
  },
  2510521707: {
    sortId: "18",
    tc: "我哋",
    yueYin: "ngo5 dei6",
    cn: "",
    pinyin: "wǒ dì",
    mandarin: "我们",
    category: "대명사 인칭대명사",
    title: "우리",
    meaning: [{ m: "우리. 1인칭 복수형" }, { e: "我哋係同學", t: "우리는 학교 친구이다" }],
    mean: "우리 우리들 저희 저희들",
  },
  2032021707: {
    sortId: "19",
    tc: "你哋",
    yueYin: "nei5 dei6",
    cn: "",
    pinyin: "nǐ dì",
    mandarin: "你们",
    category: "대명사 인칭대명사",
    title: "너희",
    meaning: [{ m: "너희. 2인칭 복수형" }, { e: "你哋做完功課未？", t: "너희 숙제는 다 했는가?" }],
    mean: "너희 너희들",
  },
  2032221707: {
    sortId: "20",
    tc: "佢哋",
    yueYin: "keoi5 dei6",
    cn: "",
    pinyin: "qú dì",
    mandarin: "他们",
    category: "대명사",
    title: "그들",
    meaning: [{ m: "그들. 3인칭 복수형." }, { e: "佢哋係同學", t: "그들은 학교 친구이다" }, { m: "이것들, 그것들. 지시대명사 복수형." }],
    mean: "그들, 그것들, 이것들",
  },
  2608926216: {
    sortId: "21",
    tc: "早晨",
    yueYin: "zou2 san4",
    cn: "",
    pinyin: "zǎo chen",
    mandarin: "早上好 早安",
    category: "인사말",
    title: "좋은 아침",
    meaning: [{ m: "아침 인사. 좋은 아침" }, { e: "老師，早晨", t: "(아침) 선생님, 안녕하세요" }],
    mean: "아침 인사. 좋은 아침",
  },
  2608921790: {
    sortId: "22",
    tc: "早唞",
    yueYin: "zou2 tau2",
    cn: "",
    pinyin: "zǎo dóu",
    mandarin: "晚安",
    category: "인사말",
    title: "안녕히 주무세요",
    meaning: [{ m: "취침 전 인사. 안녕히 주무세요 (직역 : 빨리 쉬세요)" }, { m: "(욕) 빨리 죽으세요" }],
    mean: "취침 전 인사. 안녕히 주무세요 / 욕, 빨리 죽으세요 ",
    detail: "[早抖]로 많이 쓴다",
    relevance: "早唞 早抖",
  },
  2608925238: {
    sortId: "23",
    tc: "早抖",
    yueYin: "zou2 tau2",
    cn: "",
    pinyin: "zǎo dǒu",
    mandarin: "晚安",
    category: "인사말",
    title: "안녕히 주무세요",
    meaning: [{ m: "[早唞] 취침 전 인사. 안녕히 주무세요 (직역 : 빨리 쉬세요)" }, { m: "[早唞] (욕) 빨리 죽으세요" }],
    mean: "취침 전 인사. 안녕히 주무세요 / 욕, 빨리 죽으세요 ",
    detail: "[早唞]의 오타. [抖]의 원래 발음은 [dau2]이다",
    relevance: "早唞 早抖",
  },
  3892832004: {
    sortId: "24",
    tc: "預約",
    yueYin: "jyu6 joek3",
    cn: "预约",
    pinyin: "yu yuē",
    mandarin: "",
    category: "명사 동사",
    title: "예약",
    meaning: [{ m: "예약" }, { e: "我有預約", t: "예약했다 (명사)" }, { e: "我預約咗間酒店", t: "호텔을 예약했다 (동사)" }],
    mean: "예약 예약하다",
  },
  3720224215: {
    sortId: "25",
    tc: "酒店",
    yueYin: "zau2 dim3",
    cn: "",
    pinyin: "jiǔ diàn",
    mandarin: "",
    category: "명사",
    title: "호텔",
    meaning: [{ m: "호텔" }, { e: "我book咗間酒店", t: "호텔을 예약했다 (동사)" }],
    mean: "호텔",
  },
  2723131080: {
    sortId: "26",
    tc: "機票",
    yueYin: "zau2 dim3",
    cn: "机票",
    pinyin: "jī piào",
    mandarin: "",
    category: "명사",
    title: "비행기표",
    meaning: [{ m: "비행기표, 항공권" }, { e: "訂咗機票未？", t: "비행기표 예약했나요?" }],
    mean: "비행기표 항공권",
  },
  2513838498: {
    sortId: "27",
    tc: "戲院",
    yueYin: "hei3 jyun2",
    cn: "戏院",
    pinyin: "xì yuàn",
    mandarin: "戏院 电影院 剧场 剧院",
    category: "명사",
    title: "극장/영화관",
    meaning: [{ m: "극장, 영화관" }],
    mean: "극장 영화관",
  },
  2443338498: {
    sortId: "28",
    tc: "影院",
    yueYin: "jing2 jyun2",
    cn: "",
    pinyin: "yǐng yuàn",
    mandarin: "电影院",
    category: "명사",
    title: "영화관",
    meaning: [{ m: "영화관" }],
    mean: "영화관",
  },
  3918424307: {
    sortId: "29",
    tc: "餐廳",
    yueYin: "caan1 teng1",
    cn: "餐厅",
    pinyin: "cān tīng",
    mandarin: "",
    category: "명사",
    title: "식당",
    meaning: [{ m: "식당, 레스토랑" }],
    mean: "식당 레스토랑",
  },
  2160220491: {
    sortId: "30",
    tc: "呢個",
    yueYin: "ni1 go3",
    cn: "呢个",
    pinyin: "ní gè",
    mandarin: "这个",
    category: "대명사",
    title: "이것",
    meaning: [{ m: "이것, ni1/nei1 go3 로 읽는다" }, { e: "我要呢個啊，唔該", t: "이걸로 하겠습니다. 감사합니다" }],
    mean: "이것",
    relevance: "呢個 依個",
  },
  2038120491: {
    sortId: "31",
    tc: "依個",
    yueYin: "ji1 go3",
    cn: "依个",
    pinyin: "yī gè",
    mandarin: "这个",
    category: "대명사",
    title: "이것",
    meaning: [{ m: "이것" }, { e: "我要依個啊，唔該", t: "이걸로 하겠습니다. 감사합니다" }],
    mean: "이것",
    relevance: "呢個 依個",
  },
  2160221874: {
    sortId: "32",
    tc: "呢啲",
    yueYin: "ni1 di1",
    cn: "呢啲",
    pinyin: "ní dī",
    mandarin: "这些",
    category: "대명사",
    title: "이것들",
    meaning: [{ m: "이것들. 여러개나 불가산명에 사용한다. ni1/nei1 di1 로 읽는다" }, { e: "呢啲係要寄畀佢", t: "이것들은 그에게 (택배) 붙여야 하는 것들이다" }],
    mean: "이것들",
    relevance: "呢啲 依啲",
    detail: "[呢D]로 많이 쓴다",
  },
  2038121874: {
    sortId: "33",
    tc: "依啲",
    yueYin: "ji1 di1",
    cn: "依啲",
    pinyin: "yī dī",
    mandarin: "这些",
    category: "대명사",
    title: "이것들",
    meaning: [{ m: "이것들. 여러개나 불가산명에 사용한다." }, { e: "依啲係要寄畀佢", t: "이것들은 그에게 (택배) 붙여야 하는 것들이다" }],
    mean: "이것들",
    relevance: "呢啲 依啲",
    detail: "[依D]로 많이 쓴다",
  },
  2200020491: {
    sortId: "34",
    tc: "嗰個",
    yueYin: "go2 go3",
    cn: "嗰个",
    pinyin: "gě gè",
    mandarin: "那个",
    category: "대명사",
    title: "그것",
    meaning: [{ m: "그것, 저것" }, { e: "嗰個係咩嚟㗎？", t: "저것은 무엇인가요?" }],
    mean: "그것, 저것",
    detail: "[果個]로 사용하는 사람이 있다",
  },
  2200021874: {
    sortId: "35",
    tc: "嗰啲",
    yueYin: "go2 di1",
    cn: "",
    pinyin: "gě dī",
    mandarin: "那些",
    category: "대명사",
    title: "그것들",
    meaning: [{ m: "그것들, 저것들" }, { e: "唔好理嗰啲先", t: "그것들은 우선 신경쓰지 말아라" }],
    mean: "그것들, 저것들",
    detail: "[嗰D]로 많이 사용한다. [果D]로 사용하는 사람이 있다",
  },
  2419026178: {
    sortId: "36",
    tc: "幾時",
    yueYin: "gei2 si4",
    cn: "几时",
    pinyin: "jǐ shí",
    mandarin: "什么时候",
    category: "대명사",
    title: "언제",
    meaning: [{ m: "언제" }, { e: "你幾時要？", t: "언제 필요하나요?" }],
    mean: "언제",
  },
  2419040670: {
    sortId: "37",
    tc: "幾點",
    yueYin: "gei2 dim2",
    cn: "几点",
    pinyin: "jǐ diǎn",
    mandarin: "几点 多少点",
    category: "대명사",
    title: "몇시",
    meaning: [{ m: "몇시" }, { e: "而家係幾點？", t: "지금은 몇시인가요?" }],
    mean: "몇시",
  },
  2419032784: {
    sortId: "38",
    tc: "幾耐",
    yueYin: "gei2 noi6",
    cn: "几耐",
    pinyin: "jǐ nài",
    mandarin: "多久",
    category: "대명사",
    title: "(시간)얼마",
    meaning: [{ m: "(시간) 얼마 얼마나" }, { e: "你學咗幾耐？", t: "배운지 얼마나 되었나요?" }],
    mean: "(시간) 얼마 얼마나",
  },
  2419037666: {
    sortId: "39",
    tc: "幾錢",
    yueYin: "gei2 cin2",
    cn: "几钱",
    pinyin: "jǐ qián",
    mandarin: "多少钱",
    category: "대명사",
    title: "(가격)얼마",
    meaning: [{ m: "(가격) 얼마" }, { e: "唔該，呢個幾錢啊？", t: "저기요. 이건 얼마인가요?" }],
    mean: "(가격)얼마",
  },
  2160224230: {
    sortId: "40",
    tc: "呢度",
    yueYin: "ni1 dou6",
    cn: "",
    pinyin: "ní dù",
    mandarin: "这里",
    category: "대명사",
    title: "여기",
    meaning: [{ m: "여기, 이곳 ni1/nei1 dou6 로 읽는다" }, { e: "唔該，請問呢度點去啊？", t: "저기요. 여기 어떻게 가야하나요?" }],
    mean: "여기",
    relevance: "呢度 依度",
  },
  2038124230: {
    sortId: "41",
    tc: "依度",
    yueYin: "ji1 dou6",
    cn: "",
    pinyin: "yī dù",
    mandarin: "这里",
    category: "대명사",
    title: "여기",
    meaning: [{ m: "여기, 이곳" }, { e: "唔該，請問依度點去啊？", t: "저기요. 여기 어떻게 가야하나요?" }],
    mean: "여기",
    relevance: "呢度 依度",
  },
  2200024230: {
    sortId: "42",
    tc: "嗰度",
    yueYin: "go2 dou6",
    cn: "",
    pinyin: "gě dù",
    mandarin: "那里",
    category: "대명사",
    title: "저기",
    meaning: [{ m: "저기, 저곳" }, { e: "嗰度有間cafe，入去唞下", t: "저기에 카페가 있다. 들어가서 좀 쉬자" }],
    mean: "저기, 저곳",
    detail: "[果度]로 사용하는 사람이 있다",
  },
  3700224230: {
    sortId: "43",
    tc: "邊度",
    yueYin: "bin1 dou6",
    cn: "边度",
    pinyin: "biān dù",
    mandarin: "哪里",
    category: "대명사",
    title: "어디",
    meaning: [{ m: "어디, 어느곳" }, { e: "你去咗邊度？", t: "너 어디 갔어?" }],
    mean: "어디, 어느곳",
  },
  3700220301: {
    sortId: "44",
    tc: "邊位",
    yueYin: "bin1 wai2",
    cn: "边位",
    pinyin: "biān wèi",
    mandarin: "哪位",
    category: "대명사",
    title: "어느분",
    meaning: [{ m: "어느분. 누구의 높임말" }, { e: "請問係邊位？", t: "혹시 누구신가요?" }],
    mean: "어느분 누구",
  },
  3700220491: {
    sortId: "45",
    tc: "邊個",
    yueYin: "bin1 go3",
    cn: "边个",
    pinyin: "biān gè",
    mandarin: "谁 哪个",
    category: "대명사",
    title: "누구 어느것",
    meaning: [{ m: "누구" }, { e: "佢係邊個？", t: "저 사람은 누구인가요?" }, { m: "어느것, 어떤것" }, { e: "邊個先啱啊？", t: "어떤 것이 맞는 것(정답)인가?" }],
    mean: "누구 어느것, 어떤것",
  },
};
