export const words = {
  38646: {
    tc: "零",
    syllable: "ling4",
    krSyllable: "랭",
    cn: "",
    mandarin: "líng",
    hanja: "떨어질 령(영) / 영 령(영)",
    category: "숫자",
    mean: "숫자 0(영)/적은 수량/떨어지다",
  },
  19968: {
    tc: "一",
    syllable: "jat1",
    krSyllable: "얏",
    cn: "",
    mandarin: "yī",
    hanja: "한 일",
    category: "숫자",
    mean: "숫자 1(일), 하나",
  },
  20108: {
    tc: "二",
    syllable: "yi6",
    krSyllable: "이",
    cn: "",
    mandarin: "èr",
    hanja: "두 이",
    category: "숫자",
    mean: "숫자 2(이), 둘/버금",
  },
  19977: {
    tc: "三",
    syllable: "saam1",
    krSyllable: "쌈",
    cn: "",
    mandarin: "sān",
    hanja: "석 삼",
    category: "숫자",
    mean: "숫자 3(삼), 셋/자주",
  },
  22235: {
    tc: "四",
    syllable: "sei3",
    krSyllable: "쎄이",
    cn: "",
    mandarin: "sì",
    hanja: "넉 사",
    category: "숫자",
    mean: "숫자 4(사), 넷",
  },
  20116: {
    tc: "五",
    syllable: "ng5",
    krSyllable: "응",
    cn: "",
    mandarin: "wǔ",
    hanja: "다섯 오",
    category: "숫자",
    mean: "숫자 5(오), 다섯",
  },
  20845: {
    tc: "六",
    syllable: "luk6",
    krSyllable: "록",
    cn: "",
    mandarin: "liù",
    hanja: "여섯 륙(육)",
    category: "숫자",
    mean: "숫자 6(육), 여섯",
  },
  19971: {
    tc: "七",
    syllable: "cat1",
    krSyllable: "찻",
    cn: "",
    mandarin: "qī",
    hanja: "일곱 칠",
    category: "숫자",
    mean: "숫자 7(칠), 일곱",
  },
  20843: {
    tc: "八",
    syllable: "baat3",
    krSyllable: "빳",
    cn: "",
    mandarin: "bā",
    hanja: "여덟 팔",
    category: "숫자",
    mean: "숫자 8(팔), 여덟",
  },
  20061: {
    tc: "九",
    syllable: "gau2",
    krSyllable: "까우",
    cn: "",
    mandarin: "jiǔ",
    hanja: "아홉 구",
    category: "숫자",
    mean: "숫자 9(구), 아홉",
  },
  21313: {
    tc: "十",
    syllable: "sap6",
    krSyllable: "쌉",
    cn: "",
    mandarin: "shí",
    hanja: "열 십",
    category: "숫자",
    mean: "숫자 10(십), 열",
  },
  30334: {
    tc: "百",
    syllable: "baak3",
    krSyllable: "빡",
    cn: "",
    mandarin: "bǎi",
    hanja: "일백 백, 힘쓸 맥",
    category: "숫자",
    mean: "숫자 100(백)/종류가 많음",
  },
  21315: {
    tc: "千",
    syllable: "cin1",
    krSyllable: "친",
    cn: "",
    mandarin: "qiān",
    hanja: "일천 천/밭두둑 천/그네 천",
    category: "숫자",
    mean: "숫자 1000(천)/그네",
  },
  33836: {
    tc: "萬",
    syllable: "maan6",
    krSyllable: "만",
    cn: "万",
    mandarin: "wàn mò",
    hanja: "일 만 만",
    category: "숫자",
    mean: "숫자 10000(만)/매우 많음, 높음",
  },
};
