export const words = {
  38646: {
    tc: "屋企",
    yueYin: "ok kei",
    cn: "",
    mandarin: "wu qi",
    hanja: "",
    category: "명사",
    title: "집",
    mean: "집",
  },
  38646: {
    tc: "零",
    yueYin: "ling4",
    cn: "",
    mandarin: "líng",
    hanja: "떨어질 령(영) / 영 령(영)",
    category: "숫자",
    title: "숫자 0",
    mean: "숫자 0(영)/적은 수량/떨어지다",
  },
  19968: {
    tc: "一",
    yueYin: "jat1",
    cn: "",
    mandarin: "yī",
    hanja: "한 일",
    category: "숫자",
    title: "숫자 1",
    mean: "숫자 1(일), 하나",
  },
  20108: {
    tc: "二",
    yueYin: "ji6",
    cn: "",
    mandarin: "èr",
    hanja: "두 이",
    category: "숫자",
    title: "숫자 2",
    mean: "숫자 2(이), 둘/버금",
  },
  19977: {
    tc: "三",
    yueYin: "saam1",
    cn: "",
    mandarin: "sān",
    hanja: "석 삼",
    category: "숫자",
    title: "숫자 3",
    mean: "숫자 3(삼), 셋/자주",
  },
  22235: {
    tc: "四",
    yueYin: "sei3",
    cn: "",
    mandarin: "sì",
    hanja: "넉 사",
    category: "숫자",
    title: "숫자 4",
    mean: "숫자 4(사), 넷",
  },
  20116: {
    tc: "五",
    yueYin: "ng5",
    cn: "",
    mandarin: "wǔ",
    hanja: "다섯 오",
    category: "숫자",
    title: "숫자 5",
    mean: "숫자 5(오), 다섯",
  },
  20845: {
    tc: "六",
    yueYin: "luk6",
    cn: "",
    mandarin: "liù",
    hanja: "여섯 륙(육)",
    category: "숫자",
    title: "숫자 6",
    mean: "숫자 6(육), 여섯",
  },
  19971: {
    tc: "七",
    yueYin: "cat1",
    cn: "",
    mandarin: "qī",
    hanja: "일곱 칠",
    category: "숫자",
    title: "숫자 7",
    mean: "숫자 7(칠), 일곱",
  },
  20843: {
    tc: "八",
    yueYin: "baat3",
    cn: "",
    mandarin: "bā",
    hanja: "여덟 팔",
    category: "숫자",
    title: "숫자 8",
    mean: "숫자 8(팔), 여덟",
  },
  20061: {
    tc: "九",
    yueYin: "gau2",
    cn: "",
    mandarin: "jiǔ",
    hanja: "아홉 구",
    category: "숫자",
    title: "숫자 9",
    mean: "숫자 9(구), 아홉",
  },
  21313: {
    tc: "十",
    yueYin: "sap6",
    cn: "",
    mandarin: "shí",
    hanja: "열 십",
    category: "숫자",
    title: "숫자 10",
    mean: "숫자 10(십), 열",
  },
  30334: {
    tc: "百",
    yueYin: "baak3",
    cn: "",
    mandarin: "bǎi",
    hanja: "일백 백, 힘쓸 맥",
    category: "숫자",
    title: "숫자 100",
    mean: "숫자 100(백)/종류가 많음",
  },
  21315: {
    tc: "千",
    yueYin: "cin1",
    cn: "",
    mandarin: "qiān",
    hanja: "일천 천/밭두둑 천/그네 천",
    category: "숫자",
    title: "숫자 1000",
    mean: "숫자 1000(천)/그네",
  },
  33836: {
    tc: "萬",
    yueYin: "maan6",
    cn: "万",
    mandarin: "wàn mò",
    hanja: "일 만 만",
    category: "숫자",
    title: "숫자 10000",
    mean: "숫자 10000(만)/매우 많음, 높음",
  },
};
