import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DogKaeBi Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head>
        <link rel="icon" href="/next.svg" sizes="any" />
        {/* 임시 파피콘 */}
      </head>
      <body className={inter.className}>
        <div className="max-w-7xl mx-auto relative">
          <Navigation />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
