
import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from './components/Navigation'
import Heros from './components/Heros'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className='container mx-auto'>
          <div className='flex justify-between items-center'>
            <p>logo</p>
            <Navigation/>
          </div>
          <Heros/>
          <div>{children}</div>
        </div>
      </body>
    </html>
  )
}
