const syllable = {
  initial: {
    "-": {
      pronunciation: `없음`,
      detail: `엄밀히는 성모(聲母)가 아닌 성모가 없을 때의 표기 방식이다./운모 자체가 월음(粵音)인 경우이다`,
    },
    b: {
      pronunciation: `ㅃ`,
      detail: `한국어의 [ㅂ], [ㅃ]의 발음과 유사하다./특정 조합에 따라서 [ㅂ] 혹 [ㅃ]로 들릴 수 있다./하지만 실제는 두 발음의 중간음이다.`,
    },
    p: { pronunciation: `ㅍ`, detail: `` },
    m: {
      pronunciation: `ㅁ`,
      detail: `성모(聲母)이면서 운모(韻母)인 발음이다./성모로 사용할 때 [ㅁ] 발음이고, 운모일 때 [음] 발음이다`,
    },
    f: {
      pronunciation: `f`,
      detail: `한글에는 없는 발음이다. /[ㅎ]과 [ㅍ]의 중간음으로 앞니로 밑 입술을 물면 나오는 발음이다.`,
    },
    d: { pronunciation: `ㄷ`, detail: `[ㄷ]과 [ㄸ]의 중간음이다.` },
    t: { pronunciation: `ㅌ`, detail: `` },
    n: { pronunciation: `ㄴ`, detail: `` },
    l: { pronunciation: `ㄹ`, detail: `` },
    g: { pronunciation: `ㄱ`, detail: `[ㄱ]과 [ㄲ]의 중간음이다.` },
    k: { pronunciation: `ㅋ`, detail: `` },
    ng: {
      pronunciation: `으/응`,
      detail: `한국어에 없는 발음이다. [으,은,응]의 중간 발음이다./성모(聲母)와 운모(韻母)로 사용된다. /성모의 예시로 ngaa의 경우 빠르게 [아]로 들리지만, 실제로는 [으아]의 발음이다. /운모일 때는 [은]발음으로 사용된다.`,
    },
    h: { pronunciation: `ㅎ`, detail: `` },
    gw: { pronunciation: `구`, detail: `` },
    kw: { pronunciation: `쿠`, detail: `` },
    w: { pronunciation: `우`, detail: `` },
    z: { pronunciation: `ㅈ`, detail: `` },
    c: { pronunciation: `ㅊ`, detail: `` },
    s: { pronunciation: `ㅅ`, detail: `` },
    j: {
      pronunciation: `이`,
      detail: `영어 발음 표기법과 같게 [j]는 [이] 발음이 난다./(Jacob이 제이콥이 아닌 야곱인 이유)`,
    },
  },
  vowel: {
    aa: {
      pronunciation: `아~ [aː]`,
      detail: `[아]의 긴 발음이다. 모든 성모(聲母)와 조합이 가능한 운모(韻母) 3개 중 하나이다.`,
    },
    aai: {
      pronunciation: `아~이 [aːi]`,
      detail: ``,
    },
    aau: {
      pronunciation: `아~우 [aːuː]`,
      detail: ``,
    },
    aam: {
      pronunciation: `암~ [aːm]`,
      detail: ``,
    },
    aan: {
      pronunciation: `안~ [aːn]`,
      detail: ``,
    },
    aang: {
      pronunciation: `앙~ [aːŋ]`,
      detail: ``,
    },
    aap: {
      pronunciation: `압~ [aːp̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    aat: {
      pronunciation: `앗~ [aːt̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    aak: {
      pronunciation: `악~ [aːk̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    ai: {
      pronunciation: `아이 [ɐi]`,
      detail: ``,
    },
    au: {
      pronunciation: `아우 [ɐuː]`,
      detail: ``,
    },
    am: {
      pronunciation: `암 [ɐm]`,
      detail: ``,
    },
    an: {
      pronunciation: `안 [ɐn]`,
      detail: ``,
    },
    ang: {
      pronunciation: `앙 [ɐŋ]`,
      detail: ``,
    },
    ap: {
      pronunciation: `압 [ɐp̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    at: {
      pronunciation: `앗 [ɐt̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    ak: {
      pronunciation: `악 [ɐk̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    e: {
      pronunciation: `에 [ɛː]`,
      detail: `[ㅓ]가 아닌 [에] 발음이다`,
    },
    ei: {
      pronunciation: `에이 [ɛːi]`,
      detail: ``,
    },
    eu: {
      pronunciation: `에우 [ɛːuː]`,
      detail: `[eu]는 [deu6] 한가지 조합만 존재한다.`,
    },
    em: {
      pronunciation: `엠 [ɛːm]`,
      detail: `[em]은 [lem2] 한가지 조합만 존재한다.`,
    },
    eng: {
      pronunciation: `엥~ [ɛːŋ]`,
      detail: `[eng]과 [ing]은 똑 같은 [엥]발음이 난다. 하지만 [eng]은 긴음이고 [ing]은 짧은 음이다.`,
    },
    ep: {
      pronunciation: `엡 [ep̚]`,
      detail: `[ep]은 [gep6] 한가지 조합만 존재한다. 입음(入音) 중 하나이다.`,
    },
    ek: {
      pronunciation: `엑 [ek̚]`,
      detail: `입음(入音) 중 하나이다. 받침음이 [p, t, k]인 경우 입음이다. 입음은 1, 3, 6 성만 존재한다. 광둥어에서 6성9조(六聲九調)의 6성보다 3개 많은 3조가 여기에 속한다.`,
    },
    i: {
      pronunciation: `이 [iː]`,
      detail: ``,
    },
    iu: {
      pronunciation: `이우 [iːuː]`,
      detail: ``,
    },
    im: {
      pronunciation: `임 [iːm]`,
      detail: ``,
    },
    in: {
      pronunciation: `인 [iːn]`,
      detail: ``,
    },
    ing: {
      pronunciation: `잉 [iːŋ]`,
      detail: ``,
    },
    ip: {
      pronunciation: `입 [ɪp̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    it: {
      pronunciation: `잇 [ɪt̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    ik: {
      pronunciation: `익 [ɪk̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    o: {
      pronunciation: `오ㅓ [ɔː]`,
      detail: `한글에 없는 발음이다. [오]하는 입으로 [어]를 말할 때 발음 된다`,
    },
    oi: {
      pronunciation: `오ㅓ이 [ɔːiː]`,
      detail: ``,
    },
    ou: {
      pronunciation: `오ㅓ우 [ɔːuː]`,
      detail: ``,
    },
    on: {
      pronunciation: `오언 [ɔːn]`,
      detail: ``,
    },
    ong: {
      pronunciation: `오엉 [ɔːŋ]`,
      detail: ``,
    },
    ot: {
      pronunciation: `오엇 [ot̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    ok: {
      pronunciation: `오억 [ok̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    oe: {
      pronunciation: `여 [œː]`,
      detail: `[oe]는 [여] 발음이 난다.`,
    },
    oeng: {
      pronunciation: `영 [œːŋ]`,
      detail: ``,
    },
    oek: {
      pronunciation: `역 [œːk̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    eoi: {
      pronunciation: `오이 [ɵiː]`,
      detail: `[eo]는 [오] 발음이 난다.`,
    },
    eon: {
      pronunciation: `온 [ɵn]`,
      detail: ``,
    },
    eot: {
      pronunciation: `옷 [ɵt̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    u: {
      pronunciation: `우 [uː]`,
      detail: ``,
    },
    ui: {
      pronunciation: `우이 [uːiː]`,
      detail: ``,
    },
    un: {
      pronunciation: `운 [uːn]`,
      detail: ``,
    },
    ung: {
      pronunciation: `웅 [uːŋ]`,
      detail: ``,
    },
    ut: {
      pronunciation: `웃 [ʊt̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    uk: {
      pronunciation: `욱 [ʊk̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    yu: {
      pronunciation: `위 [yːuː]`,
      detail: ``,
    },
    yun: {
      pronunciation: `윈 [yːuːn]`,
      detail: ``,
    },
    yut: {
      pronunciation: `윗 [yːʊt̚]`,
      detail: `받침음이 [p, t, k]인 입음이다. /입음은 1, 3, 6 성만 존재한다. /광둥어 성조 9성6조(九聲六調)의 3개 많은 3성이 입성이다.`,
    },
    m: {
      pronunciation: ``,
      detail: ``,
    },
    ng: {
      pronunciation: ``,
      detail: ``,
    },
  },
  yueYin: {
    aa: { tone: [1, 2, 3, 4], pronunciation: `아~`, han: `啊` },
    baa: { tone: [1, 2, 3, 6], pronunciation: `빠~`, han: `巴` },
    paa: { tone: [1, 3, 4], pronunciation: `파~`, han: `扒` },
    maa: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `마~`, han: `媽` },
    faa: { tone: [1, 3, 4], pronunciation: `fㅏ~`, han: `花` },
    daa: { tone: [1, 2], pronunciation: `따~`, han: `打` },
    taa: { tone: [1], pronunciation: `타~`, han: `他` },
    naa: { tone: [1, 4, 5, 6], pronunciation: `나~`, han: `拿` },
    laa: { tone: [1, 3], pronunciation: `라~`, han: `啦` },
    gaa: { tone: [1, 2, 3, 4], pronunciation: `까~`, han: `家` },
    kaa: { tone: [1, 2, 3], pronunciation: `카~`, han: `卡` },
    ngaa: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `은아~`, han: `牙` },
    haa: { tone: [1, 2, 4, 5, 6], pronunciation: `하~`, han: `下` },
    gwaa: { tone: [1, 2, 3], pronunciation: `꽈~`, han: `掛` },
    kwaa: { tone: [1, 2, 3], pronunciation: `콰~`, han: `誇` },
    waa: { tone: [1, 2, 4, 5, 6], pronunciation: `와~`, han: `華` },
    zaa: { tone: [1, 2, 3, 6], pronunciation: `짜~`, han: `渣` },
    caa: { tone: [1, 3, 4], pronunciation: `차~`, han: `查` },
    saa: { tone: [1, 2, 3, 4], pronunciation: `싸~`, han: `沙` },
    jaa: { tone: [5, 6], pronunciation: `야~`, han: `也` },
    aai: { tone: [1, 2, 3], pronunciation: `아~이`, han: `挨` },
    baai: { tone: [1, 2, 3, 6], pronunciation: `빠~이`, han: `拜` },
    paai: { tone: [3, 4], pronunciation: `파~이`, han: `排` },
    maai: { tone: [4, 5, 6], pronunciation: `마~이`, han: `埋` },
    faai: { tone: [3], pronunciation: `fㅏ~이`, han: `快` },
    daai: { tone: [1, 2, 3, 6], pronunciation: `따~이`, han: `帶` },
    taai: { tone: [1, 3, 5], pronunciation: `타~이`, han: `太` },
    naai: { tone: [1, 4, 5, 6], pronunciation: `나~이`, han: `嬭` },
    laai: { tone: [1, 2, 3, 6], pronunciation: `라~이`, han: `拉` },
    gaai: { tone: [1, 2, 3], pronunciation: `까~이`, han: `戒` },
    kaai: { tone: [2], pronunciation: `카~이`, han: `楷` },
    ngaai: { tone: [1, 3, 4, 6], pronunciation: `은아~이`, han: `睚` },
    haai: { tone: [1, 4, 5, 6], pronunciation: `하~이`, han: `鞋` },
    gwaai: { tone: [1, 2, 3], pronunciation: `꽈~이`, han: `罫` },
    kwaai: { tone: [3], pronunciation: `콰~이`, han: `嘳` },
    waai: { tone: [1, 2, 4, 6], pronunciation: `와~이`, han: `懷` },
    zaai: { tone: [1, 3, 6], pronunciation: `짜~이`, han: `齋` },
    caai: { tone: [1, 2, 3, 4], pronunciation: `차~이`, han: `柴` },
    saai: { tone: [1, 2, 3, 5], pronunciation: `싸~이`, han: `曬` },
    jaai: { tone: [2], pronunciation: `야~이`, han: `踹` },
    aau: { tone: [1, 2, 3], pronunciation: `아~우`, han: `拗` },
    baau: { tone: [1, 2, 3, 6], pronunciation: `빠~우`, han: `苞` },
    paau: { tone: [1, 2, 3, 4], pronunciation: `파~우`, han: `拋` },
    maau: { tone: [1, 4, 5, 6], pronunciation: `마~우`, han: `卯` },
    naau: { tone: [4, 5, 6], pronunciation: `나~우`, han: `鬧` },
    laau: { tone: [1, 4], pronunciation: `라~우`, han: `撈` },
    gaau: { tone: [1, 2, 3], pronunciation: `까~우`, han: `教` },
    kaau: { tone: [3], pronunciation: `카~우`, han: `靠` },
    ngaau: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `은아~우`, han: `爻` },
    haau: { tone: [1, 2, 3, 4, 6], pronunciation: `하~우`, han: `巧` },
    zaau: { tone: [1, 2, 3, 6], pronunciation: `짜~우`, han: `爪` },
    caau: { tone: [1, 2, 3, 4], pronunciation: `차~우`, han: `巢` },
    saau: { tone: [1, 2, 3], pronunciation: `싸~우`, han: `筲` },
    aam: { tone: [1, 2], pronunciation: `암~`, han: `菡` },
    daam: { tone: [1, 2, 3, 6], pronunciation: `땀~`, han: `擔` },
    taam: { tone: [1, 2, 3, 4, 5], pronunciation: `탐~`, han: `探` },
    naam: { tone: [1, 4, 5], pronunciation: `남~`, han: `男` },
    laam: { tone: [2, 4, 5, 6], pronunciation: `람~`, han: `攬` },
    gaam: { tone: [1, 2, 3], pronunciation: `깜~`, han: `監` },
    ngaam: { tone: [4], pronunciation: `은암~`, han: `啽` },
    haam: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `함~`, han: `咸` },
    zaam: { tone: [1, 2, 3, 6], pronunciation: `잠~`, han: `簪` },
    caam: { tone: [1, 2, 3, 4, 5], pronunciation: `참~`, han: `慘` },
    saam: { tone: [1, 2, 3], pronunciation: `쌈~`, han: `三` },
    aan: { tone: [1, 2, 3], pronunciation: `안~`, han: `晏` },
    baan: { tone: [1, 2, 3, 6], pronunciation: `빤~`, han: `班` },
    paan: { tone: [1, 3], pronunciation: `판~`, han: `攀` },
    maan: { tone: [4, 5, 6], pronunciation: `만~`, han: `晚` },
    faan: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `f안~`, han: `繁` },
    daan: { tone: [1, 2, 3, 6], pronunciation: `딴~`, han: `單` },
    taan: { tone: [1, 2, 3, 4], pronunciation: `탄~`, han: `檀` },
    naan: { tone: [2, 4, 5, 6], pronunciation: `난~`, han: `難` },
    laan: { tone: [1, 4, 5, 6], pronunciation: `란~`, han: `讕` },
    gaan: { tone: [1, 2, 3], pronunciation: `깐~`, han: `艱` },
    ngaan: { tone: [3, 4, 5, 6], pronunciation: `은안~`, han: `眼` },
    haan: { tone: [1, 4, 5, 6], pronunciation: `한~`, han: `閒` },
    gwaan: { tone: [1, 3], pronunciation: `꽌~`, han: `關` },
    waan: { tone: [1, 2, 4, 5, 6], pronunciation: `완~`, han: `還` },
    zaan: { tone: [2, 3, 6], pronunciation: `짠~`, han: `讚` },
    caan: { tone: [1, 2, 3, 4], pronunciation: `찬~`, han: `殘` },
    saan: { tone: [1, 2, 3, 4], pronunciation: `싼~`, han: `山` },
    aang: { tone: [1], pronunciation: `앙~`, han: `罌` },
    baang: { tone: [6], pronunciation: `빵~`, han: `唪` },
    paang: { tone: [1, 4, 5], pronunciation: `팡~`, han: `鵬` },
    maang: { tone: [1, 4, 5, 6], pronunciation: `망~`, han: `猛` },
    laang: { tone: [5], pronunciation: `랑~`, han: `冷` },
    gaang: { tone: [1, 3], pronunciation: `깡~`, han: `更` },
    ngaang: { tone: [1, 6], pronunciation: `은앙~`, han: `硬` },
    haang: { tone: [1, 4], pronunciation: `항~`, han: `夯` },
    gwaang: { tone: [2, 6], pronunciation: `꽝~`, han: `逛` },
    kwaang: { tone: [1, 3], pronunciation: `쾅~`, han: `眶` },
    waang: { tone: [4, 6], pronunciation: `왕~`, han: `橫` },
    zaang: { tone: [1, 3, 6], pronunciation: `짱~`, han: `諍` },
    caang: { tone: [1, 2, 3, 4], pronunciation: `창`, han: `撐` },
    saang: { tone: [1, 2], pronunciation: `쌍`, han: `生` },
    aap: { tone: [3], pronunciation: `압~`, han: `鴨` },
    daap: { tone: [1, 3, 6], pronunciation: `땁~`, han: `答` },
    taap: { tone: [3], pronunciation: `탑~`, han: `塌` },
    naap: { tone: [6], pronunciation: `납~`, han: `納` },
    laap: { tone: [3, 6], pronunciation: `랍~`, han: `臘` },
    gaap: { tone: [3], pronunciation: `깝~`, han: `甲` },
    ngaap: { tone: [3], pronunciation: `으압~`, han: `押` },
    haap: { tone: [3, 6], pronunciation: `합~`, han: `狹` },
    zaap: { tone: [3, 6], pronunciation: `짭~`, han: `集` },
    caap: { tone: [3], pronunciation: `찹~`, han: `插` },
    saap: { tone: [3, 6], pronunciation: `쌉~`, han: `翣` },
    aat: { tone: [3], pronunciation: `앗~`, han: `壓` },
    baat: { tone: [3, 6], pronunciation: `밧~`, han: `扒` },
    maat: { tone: [3, 6], pronunciation: `맛~`, han: `抹` },
    faat: { tone: [3], pronunciation: `f앗~`, han: `發` },
    daat: { tone: [3, 6], pronunciation: `땃~`, han: `達` },
    taat: { tone: [3], pronunciation: `탓~`, han: `躂` },
    naat: { tone: [3, 6], pronunciation: `낫~`, han: `捺` },
    laat: { tone: [6], pronunciation: `랏~`, han: `辣` },
    gaat: { tone: [3], pronunciation: `깟~`, han: `戛` },
    kaat: { tone: [1], pronunciation: `캇`, han: `卡` },
    ngaat: { tone: [3, 6], pronunciation: `으앗~`, han: `扤` },
    gwaat: { tone: [3], pronunciation: `괏~`, han: `刮` },
    waat: { tone: [3, 6], pronunciation: `왓~`, han: `滑` },
    zaat: { tone: [3, 6], pronunciation: `짯~`, han: `扎` },
    caat: { tone: [3], pronunciation: `찻~`, han: `察` },
    saat: { tone: [3], pronunciation: `쌋~`, han: `殺` },
    aak: { tone: [1, 3], pronunciation: `악~`, han: `軛` },
    baak: { tone: [1, 3, 6], pronunciation: `빡~`, han: `帛` },
    paak: { tone: [1, 3], pronunciation: `팍~`, han: `拍` },
    maak: { tone: [1, 3, 6], pronunciation: `막~`, han: `擘` },
    faak: { tone: [3], pronunciation: `f악~`, han: `謋` },
    daak: { tone: [1], pronunciation: `딱~`, han: `咑` },
    laak: { tone: [6], pronunciation: `락~`, han: `勒` },
    gaak: { tone: [3], pronunciation: `깍~`, han: `革` },
    kaak: { tone: [1, 3], pronunciation: `칵~`, han: `緙` },
    ngaak: { tone: [1, 3, 6], pronunciation: `으악~`, han: `額` },
    haak: { tone: [1, 3], pronunciation: `학~`, han: `客` },
    gwaak: { tone: [3], pronunciation: `꽉~`, han: `摑` },
    waak: { tone: [6], pronunciation: `왁~`, han: `畫` },
    zaak: { tone: [3, 6], pronunciation: `짝~`, han: `澤` },
    caak: { tone: [1, 3, 6], pronunciation: `착~`, han: `賊` },
    saak: { tone: [3], pronunciation: `싹~`, han: `索` },
    jaak: { tone: [3], pronunciation: `약~`, han: `喫` },
    ai: { tone: [1, 2, 3], pronunciation: `아이`, han: `矮` },
    bai: { tone: [1, 3, 6], pronunciation: `빠이`, han: `閉` },
    pai: { tone: [1, 3, 5], pronunciation: `파이`, han: `批` },
    mai: { tone: [1, 3, 4, 5, 6], pronunciation: `마이`, han: `迷` },
    fai: { tone: [1, 2, 3, 6], pronunciation: `fㅏ이`, han: `費` },
    dai: { tone: [1, 2, 3, 6], pronunciation: `따이`, han: `弟` },
    tai: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `타이`, han: `體` },
    nai: { tone: [4, 5, 6], pronunciation: `나이`, han: `泥` },
    lai: { tone: [2, 4, 5, 6], pronunciation: `라이`, han: `禮` },
    gai: { tone: [1, 2, 3, 6], pronunciation: `까이`, han: `雞` },
    kai: { tone: [1, 2, 3], pronunciation: `카이`, han: `啟` },
    ngai: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `은아이`, han: `危` },
    hai: { tone: [1, 4, 5, 6], pronunciation: `하이`, han: `兮` },
    gwai: { tone: [1, 2, 3, 6], pronunciation: `꽈이`, han: `歸` },
    kwai: { tone: [1, 2, 3, 4, 5], pronunciation: `콰이`, han: `規` },
    wai: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `와이`, han: `遺` },
    zai: { tone: [1, 2, 3, 6], pronunciation: `짜이`, han: `祭` },
    cai: { tone: [1, 2, 3, 4, 5], pronunciation: `차이`, han: `齊` },
    sai: { tone: [1, 2, 3, 6], pronunciation: `싸이`, han: `勢` },
    jai: { tone: [5, 6], pronunciation: `야이`, han: `曳` },
    au: { tone: [1, 2, 3], pronunciation: `아우`, han: `漚` },
    bau: { tone: [6], pronunciation: `빠우`, han: `堷` },
    pau: { tone: [2, 3, 4], pronunciation: `파우`, han: `剖` },
    mau: { tone: [1, 3, 4, 5, 6], pronunciation: `마우`, han: `侔` },
    fau: { tone: [1, 2, 4, 6], pronunciation: `fㅏ우`, han: `否` },
    dau: { tone: [1, 2, 3, 6], pronunciation: `따우`, han: `鬥` },
    tau: { tone: [1, 2, 3, 4], pronunciation: `타우`, han: `頭` },
    nau: { tone: [1, 2, 4, 5, 6], pronunciation: `나우`, han: `耨` },
    lau: { tone: [1, 4, 5, 6], pronunciation: `라우`, han: `漏` },
    gau: { tone: [1, 2, 3, 6], pronunciation: `까우`, han: `救` },
    kau: { tone: [1, 3, 4, 5], pronunciation: `카우`, han: `求` },
    ngau: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `은아우`, han: `偶` },
    hau: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `하우`, han: `後` },
    zau: { tone: [1, 2, 3, 6], pronunciation: `짜우`, han: `走` },
    cau: { tone: [1, 2, 3, 4, 5], pronunciation: `차우`, han: `醜` },
    sau: { tone: [1, 2, 3, 4, 6], pronunciation: `싸우`, han: `受` },
    jau: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `야우`, han: `褎` },
    am: { tone: [1, 2, 3], pronunciation: `암`, han: `暗` },
    bam: { tone: [1], pronunciation: `빰`, han: `泵` },
    dam: { tone: [1, 2, 3, 4], pronunciation: `땀`, han: `抌` },
    tam: { tone: [5], pronunciation: `탐`, han: `氹` },
    nam: { tone: [2, 4, 5, 6], pronunciation: `남`, han: `稔` },
    lam: { tone: [2, 4, 5, 6], pronunciation: `람`, han: `林` },
    gam: { tone: [1, 2, 3, 6], pronunciation: `깜`, han: `金` },
    kam: { tone: [1, 4, 5], pronunciation: `캄`, han: `琴` },
    ngam: { tone: [1, 2, 3, 4, 6], pronunciation: `은암`, han: `韽` },
    ham: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `함`, han: `含` },
    zam: { tone: [1, 2, 3, 6], pronunciation: `짬`, han: `寖` },
    cam: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `참`, han: `侵` },
    sam: { tone: [1, 2, 3, 4, 6], pronunciation: `쌈`, han: `心` },
    jam: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `얌`, han: `淫` },
    ban: { tone: [1, 2, 3, 6], pronunciation: `빤`, han: `品` },
    pan: { tone: [1, 3, 4, 5], pronunciation: `판`, han: `噴` },
    man: { tone: [1, 2, 4, 5, 6], pronunciation: `만`, han: `問` },
    fan: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `f안`, han: `分` },
    dan: { tone: [1, 2, 3, 6], pronunciation: `딴`, han: `躉` },
    tan: { tone: [1, 3, 4], pronunciation: `탄`, han: `吞` },
    nan: { tone: [2], pronunciation: `난`, han: `捻` },
    gan: { tone: [1, 2, 3, 6], pronunciation: `깐`, han: `根` },
    kan: { tone: [4, 5], pronunciation: `칸`, han: `芹` },
    ngan: { tone: [1, 3, 4, 6], pronunciation: `은안`, han: `銀` },
    han: { tone: [2, 4, 6], pronunciation: `한`, han: `恨` },
    gwan: { tone: [1, 2, 3, 6], pronunciation: `꽌`, han: `軍` },
    kwan: { tone: [1, 2, 3, 4, 5], pronunciation: `콴`, han: `困` },
    wan: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `완`, han: `溫` },
    zan: { tone: [1, 2, 3, 6], pronunciation: `짠`, han: `震` },
    can: { tone: [1, 2, 3, 4], pronunciation: `찬`, han: `陳` },
    san: { tone: [1, 4, 5, 6], pronunciation: `싼`, han: `神` },
    jan: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `얀`, han: `引` },
    ang: { tone: [1, 2], pronunciation: `앙`, han: `鶯` },
    bang: { tone: [1, 2, 6], pronunciation: `빵`, han: `崩` },
    pang: { tone: [2, 4], pronunciation: `팡`, han: `堋` },
    mang: { tone: [2, 4], pronunciation: `망`, han: `盟` },
    fang: { tone: [4], pronunciation: `f앙`, han: `揈` },
    dang: { tone: [1, 2, 3, 6], pronunciation: `땅`, han: `等` },
    tang: { tone: [4], pronunciation: `탕`, han: `騰` },
    nang: { tone: [4], pronunciation: `낭`, han: `能` },
    lang: { tone: [1], pronunciation: `랑`, han: `舲` },
    gang: { tone: [1, 2, 3], pronunciation: `깡`, han: `庚` },
    kang: { tone: [2, 3], pronunciation: `캉`, han: `掯` },
    ngang: { tone: [1, 2], pronunciation: `으앙`, han: `罃` },
    hang: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `항`, han: `幸` },
    gwang: { tone: [1], pronunciation: `꽝`, han: `觥` },
    wang: { tone: [4], pronunciation: `쾅`, han: `宏` },
    zang: { tone: [1, 3, 6], pronunciation: `짱`, han: `爭` },
    cang: { tone: [1, 3, 4], pronunciation: `창`, han: `層` },
    sang: { tone: [1, 3], pronunciation: `쌍`, han: `蹭` },
    ap: { tone: [1], pronunciation: `압`, han: `洽` },
    dap: { tone: [1], pronunciation: `땁`, han: `耷` },
    nap: { tone: [1], pronunciation: `납`, han: `粒` },
    lap: { tone: [1, 6], pronunciation: `랍`, han: `立` },
    gap: { tone: [1, 3, 6], pronunciation: `깝`, han: `急` },
    kap: { tone: [1, 6], pronunciation: `캅`, han: `吸` },
    ngap: { tone: [1, 6], pronunciation: `으압`, han: `岋` },
    hap: { tone: [1, 6], pronunciation: `합`, han: `合` },
    zap: { tone: [1, 6], pronunciation: `짭`, han: `執` },
    cap: { tone: [1], pronunciation: `찹`, han: `輯` },
    sap: { tone: [1, 6], pronunciation: `쌉`, han: `拾` },
    jap: { tone: [1, 6], pronunciation: `얍`, han: `潝` },
    bat: { tone: [1, 6], pronunciation: `빳`, han: `筆` },
    pat: { tone: [1], pronunciation: `팟`, han: `匹` },
    mat: { tone: [1, 6], pronunciation: `맛`, han: `密` },
    fat: { tone: [1, 3, 6], pronunciation: `f앗`, han: `紼` },
    dat: { tone: [1, 6], pronunciation: `땃`, han: `突` },
    nat: { tone: [6], pronunciation: `낫`, han: `吶` },
    lat: { tone: [1], pronunciation: `랏`, han: `甩` },
    gat: { tone: [1, 6], pronunciation: `깟`, han: `吉` },
    kat: { tone: [1], pronunciation: `캇`, han: `咳` },
    ngat: { tone: [1, 6], pronunciation: `으앗`, han: `兀` },
    hat: { tone: [1, 6], pronunciation: `핫`, han: `瞎` },
    gwat: { tone: [1, 6], pronunciation: `꽛`, han: `骨` },
    wat: { tone: [1, 6], pronunciation: `쾃`, han: `屈` },
    zat: { tone: [1, 6], pronunciation: `짯`, han: `質` },
    cat: { tone: [1], pronunciation: `찻`, han: `七` },
    sat: { tone: [1, 6], pronunciation: `쌋`, han: `實` },
    jat: { tone: [1, 6], pronunciation: `얏`, han: `日` },
    ak: { tone: [1], pronunciation: `악`, han: `偓` },
    bak: { tone: [1], pronunciation: `빡`, han: `北` },
    mak: { tone: [1, 3, 6], pronunciation: `팍`, han: `默` },
    dak: { tone: [1, 6], pronunciation: `딱`, han: `得` },
    nak: { tone: [6], pronunciation: `낙`, han: `疒` },
    lak: { tone: [6], pronunciation: `락`, han: `勒` },
    ngak: { tone: [1], pronunciation: `으악`, han: `呃` },
    hak: { tone: [1], pronunciation: `학`, han: `黑` },
    zak: { tone: [1], pronunciation: `짝`, han: `側` },
    cak: { tone: [1], pronunciation: `착`, han: `測` },
    sak: { tone: [1], pronunciation: `싹`, han: `塞` },
    e: { tone: [6], pronunciation: `에`, han: `誒` },
    be: { tone: [1], pronunciation: `뻬`, han: `啤` },
    me: { tone: [1, 2, 5], pronunciation: `메`, han: `乜` },
    fe: { tone: [1], pronunciation: `fㅔ`, han: `啡` },
    de: { tone: [1, 2], pronunciation: `떼`, han: `爹` },
    ne: { tone: [1, 6], pronunciation: `네`, han: `呢` },
    le: { tone: [1, 2, 4, 5], pronunciation: `레`, han: `咧` },
    ge: { tone: [1], pronunciation: `께`, han: `痂` },
    ke: { tone: [1, 4], pronunciation: `케`, han: `伽` },
    ze: { tone: [1, 2, 3, 5, 6], pronunciation: `쩨`, han: `謝` },
    ce: { tone: [1, 2, 3, 4], pronunciation: `체`, han: `邪` },
    se: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `쎄`, han: `射` },
    je: { tone: [4, 5, 6], pronunciation: `예`, han: `夜` },
    ei: { tone: [6], pronunciation: `에이`, han: `欸` },
    bei: { tone: [1, 2, 3, 6], pronunciation: `뻬이`, han: `悲` },
    pei: { tone: [1, 2, 3, 4, 5], pronunciation: `페이`, han: `披` },
    mei: { tone: [1, 2, 4, 5], pronunciation: `메이`, han: `微` },
    fei: { tone: [1, 2, 4, 6], pronunciation: `fㅔ이`, han: `飛` },
    dei: { tone: [6], pronunciation: `떼이`, han: `地` },
    nei: { tone: [1, 2, 4, 5, 6], pronunciation: `네이`, han: `珥` },
    lei: { tone: [1, 4, 5, 6], pronunciation: `레이`, han: `理` },
    gei: { tone: [1, 2, 3, 6], pronunciation: `께이`, han: `機` },
    kei: { tone: [1, 2, 3, 4, 5], pronunciation: `케이`, han: `奇` },
    hei: { tone: [1, 2, 3], pronunciation: `헤이`, han: `起` },
    sei: { tone: [2, 3], pronunciation: `쎄이`, han: `死` },
    deu: { tone: [6], pronunciation: `떼우`, han: `調` },
    lem: { tone: [2], pronunciation: `렘`, han: `舐` },
    beng: { tone: [2, 3, 6], pronunciation: `뼁~`, han: `餅` },
    peng: { tone: [1, 4], pronunciation: `펭~`, han: `平` },
    meng: { tone: [2, 4, 6], pronunciation: `멩~`, han: `名` },
    deng: { tone: [1, 2, 3, 6], pronunciation: `뗑~`, han: `掟` },
    teng: { tone: [1, 3, 5], pronunciation: `텡~`, han: `廳` },
    leng: { tone: [1, 3, 4, 5], pronunciation: `렝~`, han: `靚` },
    geng: { tone: [1, 2, 3], pronunciation: `껭~`, han: `鏡` },
    heng: { tone: [1], pronunciation: `헹~`, han: `輕` },
    zeng: { tone: [1, 2, 3, 6], pronunciation: `쩽~`, han: `鄭` },
    ceng: { tone: [1, 2, 4], pronunciation: `쳉~`, han: `青` },
    seng: { tone: [1, 2, 3, 4], pronunciation: `쎙`, han: `腥` },
    jeng: { tone: [2, 4], pronunciation: `옝~`, han: `贏` },
    gep: { tone: [6], pronunciation: `껩`, han: `夾` },
    bek: { tone: [3], pronunciation: `뻭`, han: `壁` },
    pek: { tone: [3, 6], pronunciation: `펙`, han: `劈` },
    dek: { tone: [3, 6], pronunciation: `떽`, han: `笛` },
    tek: { tone: [3], pronunciation: `텍`, han: `踢` },
    lek: { tone: [1, 6], pronunciation: `렉`, han: `叻` },
    kek: { tone: [6], pronunciation: `켁`, han: `劇` },
    hek: { tone: [3], pronunciation: `헥`, han: `吃` },
    zek: { tone: [3, 6], pronunciation: `쩩`, han: `炙` },
    cek: { tone: [3], pronunciation: `첵`, han: `尺` },
    sek: { tone: [3, 6], pronunciation: `쎅`, han: `石` },
    mi: { tone: [1], pronunciation: `미`, han: `眯` },
    di: { tone: [1], pronunciation: `띠`, han: `啲` },
    ni: { tone: [1, 4], pronunciation: `니`, han: `呢` },
    li: { tone: [1], pronunciation: `리`, han: `唎` },
    zi: { tone: [1, 2, 3, 6], pronunciation: `찌`, han: `緇` },
    ci: { tone: [1, 2, 3, 4, 5], pronunciation: `치`, han: `詞` },
    si: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `씨`, han: `試` },
    ji: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `이`, han: `意` },
    biu: { tone: [1, 2, 3, 6], pronunciation: `삐우`, han: `表` },
    piu: { tone: [1, 2, 3, 4, 5], pronunciation: `피우`, han: `漂` },
    miu: { tone: [1, 4, 5, 6], pronunciation: `미우`, han: `妙` },
    fiu: { tone: [3], pronunciation: `fㅣ우`, han: `覅` },
    diu: { tone: [1, 2, 3, 6], pronunciation: `띠우`, han: `調` },
    tiu: { tone: [1, 2, 3, 4, 5], pronunciation: `티우`, han: `調` },
    niu: { tone: [1, 4, 5, 6], pronunciation: `니우`, han: `鳥` },
    liu: { tone: [1, 2, 4, 5, 6], pronunciation: `리우`, han: `了` },
    giu: { tone: [1, 2, 3, 6], pronunciation: `끼우`, han: `嬌` },
    kiu: { tone: [2, 3, 4, 5], pronunciation: `키우`, han: `橋` },
    hiu: { tone: [1, 2, 3], pronunciation: `히우`, han: `枵` },
    ziu: { tone: [1, 2, 3, 6], pronunciation: `찌우`, han: `焦` },
    ciu: { tone: [1, 2, 3, 4, 5], pronunciation: `치우`, han: `昭` },
    siu: { tone: [1, 2, 3, 4, 6], pronunciation: `씨우`, han: `消` },
    jiu: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `이우`, han: `搖` },
    dim: { tone: [1, 2, 3, 6], pronunciation: `띰`, han: `點` },
    tim: { tone: [1, 2, 3, 4, 5], pronunciation: `팀`, han: `添` },
    nim: { tone: [1, 2, 4, 5, 6], pronunciation: `님`, han: `念` },
    lim: { tone: [1, 2, 4, 5, 6], pronunciation: `림`, han: `斂` },
    gim: { tone: [1, 2, 3, 6], pronunciation: `낌`, han: `劍` },
    kim: { tone: [4], pronunciation: `킴`, han: `黔` },
    him: { tone: [1, 2, 3], pronunciation: `힘`, han: `欠` },
    zim: { tone: [1, 2, 3, 6], pronunciation: `찜`, han: `沾` },
    cim: { tone: [1, 2, 3, 4, 5], pronunciation: `침`, han: `潛` },
    sim: { tone: [1, 2, 3, 4, 6], pronunciation: `씸`, han: `禪` },
    jim: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `임`, han: `厭` },
    bin: { tone: [1, 2, 3, 6], pronunciation: `빈`, han: `辯` },
    pin: { tone: [1, 2, 3, 4, 5], pronunciation: `핀`, han: `偏` },
    min: { tone: [4, 5, 6], pronunciation: `민`, han: `面` },
    din: { tone: [1, 2, 3, 6], pronunciation: `딘`, han: `典` },
    tin: { tone: [1, 2, 3, 4, 5], pronunciation: `틴`, han: `天` },
    nin: { tone: [2, 4, 5, 6], pronunciation: `닌`, han: `年` },
    lin: { tone: [2, 4, 5, 6], pronunciation: `린`, han: `連` },
    gin: { tone: [1, 2, 3, 6], pronunciation: `낀`, han: `堅` },
    kin: { tone: [3, 4], pronunciation: `킨`, han: `虔` },
    hin: { tone: [1, 2, 3], pronunciation: `힌`, han: `顯` },
    zin: { tone: [1, 2, 3, 6], pronunciation: `찐`, han: `剪` },
    cin: { tone: [1, 2, 4, 5], pronunciation: `친`, han: `前` },
    sin: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `씬`, han: `先` },
    jin: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `인`, han: `延` },
    bing: { tone: [1, 2, 3, 6], pronunciation: `뺑`, han: `冰` },
    ping: { tone: [1, 3, 4], pronunciation: `팽`, han: `瓶` },
    ming: { tone: [4, 5, 6], pronunciation: `맹`, han: `明` },
    fing: { tone: [6], pronunciation: `f앵 (원래는 없는 음)`, han: `` },
    ding: { tone: [1, 2, 3, 6], pronunciation: `땡`, han: `訂` },
    ting: { tone: [1, 2, 3, 4, 5], pronunciation: `탱`, han: `挺` },
    ning: { tone: [1, 4, 6], pronunciation: `냉`, han: `寧` },
    ling: { tone: [1, 2, 4, 5, 6], pronunciation: `랭`, han: `領` },
    ging: { tone: [1, 2, 3, 6], pronunciation: `깽`, han: `經` },
    king: { tone: [1, 2, 4], pronunciation: `캥`, han: `傾` },
    hing: { tone: [1, 3, 5], pronunciation: `행`, han: `輕` },
    gwing: { tone: [1, 2], pronunciation: `꽹`, han: `炯` },
    wing: { tone: [1, 4, 5, 6], pronunciation: `왱`, han: `永` },
    zing: { tone: [1, 2, 3, 6], pronunciation: `쨍`, han: `晶` },
    cing: { tone: [1, 2, 3, 4], pronunciation: `챙`, han: `呈` },
    sing: { tone: [1, 2, 3, 4, 6], pronunciation: `쌩`, han: `星` },
    jing: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `얭`, han: `英` },
    dip: { tone: [3], pronunciation: `띱`, han: `碟` },
    tip: { tone: [3], pronunciation: `팁`, han: `貼` },
    nip: { tone: [1, 6], pronunciation: `닙`, han: `涅` },
    lip: { tone: [6], pronunciation: `립`, han: `獵` },
    gip: { tone: [2, 3, 6], pronunciation: `낍`, han: `劫` },
    hip: { tone: [3, 6], pronunciation: `힙`, han: `協` },
    zip: { tone: [3], pronunciation: `찝`, han: `接` },
    cip: { tone: [3], pronunciation: `칩`, han: `妾` },
    sip: { tone: [3], pronunciation: `씹`, han: `涉` },
    jip: { tone: [3, 6], pronunciation: `입`, han: `業` },
    bit: { tone: [1, 3, 6], pronunciation: `삣`, han: `必` },
    pit: { tone: [3], pronunciation: `핏`, han: `撇` },
    mit: { tone: [1, 6], pronunciation: `밋`, han: `滅` },
    dit: { tone: [1, 3, 6], pronunciation: `띳`, han: `跌` },
    tit: { tone: [3], pronunciation: `팃`, han: `鐵` },
    lit: { tone: [3, 6], pronunciation: `릿`, han: `列` },
    git: { tone: [3, 6], pronunciation: `낏`, han: `潔` },
    kit: { tone: [3], pronunciation: `킷`, han: `揭` },
    ngit: { tone: [6], pronunciation: `으잇`, han: `齧` },
    hit: { tone: [3], pronunciation: `힛`, han: `歇` },
    zit: { tone: [1, 3, 6], pronunciation: `찟`, han: `節` },
    cit: { tone: [3], pronunciation: `칫`, han: `切` },
    sit: { tone: [3, 6], pronunciation: `씻`, han: `舌` },
    jit: { tone: [3, 6], pronunciation: `잇`, han: `熱` },
    bik: { tone: [1, 3], pronunciation: `삑`, han: `碧` },
    pik: { tone: [1], pronunciation: `픽`, han: `癖` },
    mik: { tone: [6], pronunciation: `믹`, han: `覓` },
    dik: { tone: [1, 6], pronunciation: `띡`, han: `的` },
    tik: { tone: [1], pronunciation: `틱`, han: `惕` },
    nik: { tone: [1, 6], pronunciation: `닉`, han: `匿` },
    lik: { tone: [1, 6], pronunciation: `릭`, han: `力` },
    gik: { tone: [1, 6], pronunciation: `끽`, han: `極` },
    kik: { tone: [1], pronunciation: `킥`, han: `棘` },
    hik: { tone: [1], pronunciation: `힉`, han: `瞁` },
    gwik: { tone: [1], pronunciation: `뀍`, han: `馘` },
    kwik: { tone: [1], pronunciation: `퀵`, han: `隙` },
    wik: { tone: [6], pronunciation: `윅`, han: `域` },
    zik: { tone: [1, 3, 6], pronunciation: `찍`, han: `直` },
    cik: { tone: [1, 3], pronunciation: `칙`, han: `斥` },
    sik: { tone: [1, 3, 6], pronunciation: `씩`, han: `食` },
    jik: { tone: [1, 6], pronunciation: `익`, han: `亦` },
    o: { tone: [1, 2, 4], pronunciation: `오어`, han: `柯` },
    bo: { tone: [1, 2, 3], pronunciation: `뽀어`, han: `播` },
    po: { tone: [1, 2, 3, 4], pronunciation: `포어`, han: `破` },
    mo: { tone: [1, 2, 4, 5, 6], pronunciation: `모어`, han: `磨` },
    fo: { tone: [1, 2, 3, 6], pronunciation: `fㅗ어`, han: `火` },
    do: { tone: [1, 2, 3, 6], pronunciation: `또어`, han: `多` },
    to: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `토어`, han: `妥` },
    no: { tone: [1, 4, 5, 6], pronunciation: `노어`, han: `挪` },
    lo: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `로어`, han: `羅` },
    go: { tone: [1, 2, 3], pronunciation: `꼬어`, han: `哥` },
    ko: { tone: [1], pronunciation: `코어`, han: `鈳` },
    ngo: { tone: [1, 2, 4, 5, 6], pronunciation: `은어`, han: `我` },
    ho: { tone: [1, 2, 3, 4, 6], pronunciation: `호어`, han: `可` },
    gwo: { tone: [1, 2, 3], pronunciation: `꼬어`, han: `過` },
    wo: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `워`, han: `禍` },
    zo: { tone: [2, 3, 6], pronunciation: `쪼어`, han: `助` },
    co: { tone: [1, 2, 3, 4, 5], pronunciation: `초어`, han: `初` },
    so: { tone: [1, 2, 3, 4], pronunciation: `쏘어`, han: `所` },
    jo: { tone: [1], pronunciation: `요어`, han: `唷` },
    oi: { tone: [1, 2, 3], pronunciation: `어이`, han: `靉` },
    poi: { tone: [2], pronunciation: `퍼이`, han: `俖` },
    doi: { tone: [6], pronunciation: `떠이`, han: `代` },
    toi: { tone: [1, 2, 4, 5], pronunciation: `터이`, han: `胎` },
    noi: { tone: [5, 6], pronunciation: `너이`, han: `內` },
    loi: { tone: [4, 6], pronunciation: `러이`, han: `來` },
    goi: { tone: [1, 2, 3], pronunciation: `꺼이`, han: `改` },
    koi: { tone: [2, 3], pronunciation: `커이`, han: `丐` },
    ngoi: { tone: [1, 2, 3, 4, 6], pronunciation: `으어이`, han: `礙` },
    hoi: { tone: [1, 2, 4, 5, 6], pronunciation: `허이`, han: `海` },
    zoi: { tone: [1, 2, 3, 6], pronunciation: `쩌이`, han: `載` },
    coi: { tone: [1, 2, 3, 4, 6], pronunciation: `처이`, han: `才` },
    soi: { tone: [1], pronunciation: `써이`, han: `鰓` },
    ou: { tone: [1, 2, 3], pronunciation: `오우`, han: `奧` },
    bou: { tone: [1, 2, 3, 6], pronunciation: `뽀우`, han: `布` },
    pou: { tone: [1, 2, 3, 4, 5], pronunciation: `포우`, han: `鋪` },
    mou: { tone: [1, 2, 4, 5, 6], pronunciation: `모우`, han: `無` },
    dou: { tone: [1, 2, 3, 6], pronunciation: `또우`, han: `盜` },
    tou: { tone: [1, 2, 3, 4, 5], pronunciation: `토우`, han: `桃` },
    nou: { tone: [4, 5, 6], pronunciation: `노우`, han: `腦` },
    lou: { tone: [1, 2, 4, 5, 6], pronunciation: `로우`, han: `露` },
    gou: { tone: [1, 2, 3], pronunciation: `꼬우`, han: `告` },
    ngou: { tone: [1, 2, 3, 4, 6], pronunciation: `으오우`, han: `傲` },
    hou: { tone: [1, 2, 3, 4, 6], pronunciation: `호우`, han: `豪` },
    zou: { tone: [1, 2, 3, 6], pronunciation: `쪼우`, han: `皂` },
    cou: { tone: [1, 2, 3, 4, 5], pronunciation: `초우`, han: `操` },
    sou: { tone: [1, 2, 3], pronunciation: `쏘우`, han: `數` },
    jou: { tone: [1], pronunciation: `요우 (요즘 사용 안함)`, han: `𢝊` },
    on: { tone: [1, 3], pronunciation: `언`, han: `安` },
    gon: { tone: [1, 2, 3], pronunciation: `껀`, han: `干` },
    ngon: { tone: [1, 3, 6], pronunciation: `으언`, han: `岸` },
    hon: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `헌`, han: `寒` },
    ong: { tone: [1, 3], pronunciation: `엉`, han: `骯` },
    bong: { tone: [1, 2, 3, 6], pronunciation: `뻥`, han: `傍` },
    pong: { tone: [1, 3, 4, 5], pronunciation: `펑`, han: `旁` },
    mong: { tone: [1, 4, 5, 6], pronunciation: `멍`, han: `網` },
    fong: { tone: [1, 2, 3, 4], pronunciation: `f엉`, han: `防` },
    dong: { tone: [1, 2, 3, 6], pronunciation: `떵`, han: `當` },
    tong: { tone: [1, 2, 3, 4], pronunciation: `텅`, han: `堂` },
    nong: { tone: [4, 5, 6], pronunciation: `넝`, han: `囊` },
    long: { tone: [1, 4, 5, 6], pronunciation: `렁`, han: `閬` },
    gong: { tone: [1, 2, 3, 6], pronunciation: `껑`, han: `降` },
    kong: { tone: [1, 2, 3, 4], pronunciation: `컹`, han: `抗` },
    ngong: { tone: [1, 3, 4, 5, 6], pronunciation: `으엉`, han: `卬` },
    hong: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `헝`, han: `航` },
    gwong: { tone: [1, 2, 3, 6], pronunciation: `꿩`, han: `廣` },
    kwong: { tone: [3, 4], pronunciation: `퀑`, han: `曠` },
    wong: { tone: [1, 2, 4, 5, 6], pronunciation: `웡`, han: `黃` },
    zong: { tone: [1, 2, 3, 6], pronunciation: `쩡`, han: `贓` },
    cong: { tone: [1, 2, 3, 4], pronunciation: `청`, han: `藏` },
    song: { tone: [1, 2, 3], pronunciation: `썽`, han: `喪` },
    got: { tone: [3], pronunciation: `껏`, han: `割` },
    hot: { tone: [3, 6], pronunciation: `헛`, han: `喝` },
    ok: { tone: [1, 3], pronunciation: `억`, han: `堊` },
    bok: { tone: [1, 3, 6], pronunciation: `뻑`, han: `博` },
    pok: { tone: [3], pronunciation: `퍽`, han: `樸` },
    mok: { tone: [1, 3, 6], pronunciation: `먹`, han: `莫` },
    fok: { tone: [3], pronunciation: `f억`, han: `藿` },
    dok: { tone: [6], pronunciation: `떡`, han: `度` },
    tok: { tone: [3], pronunciation: `턱`, han: `託` },
    nok: { tone: [6], pronunciation: `넉`, han: `諾` },
    lok: { tone: [3, 6], pronunciation: `럭`, han: `落` },
    gok: { tone: [3], pronunciation: `꺽`, han: `覺` },
    kok: { tone: [1, 3], pronunciation: `컥`, han: `確` },
    ngok: { tone: [3, 6], pronunciation: `으억`, han: `樂` },
    hok: { tone: [3, 6], pronunciation: `헉`, han: `鶴` },
    gwok: { tone: [3], pronunciation: `꿕`, han: `國` },
    kwok: { tone: [3], pronunciation: `쿽`, han: `廓` },
    wok: { tone: [3, 6], pronunciation: `웍`, han: `獲` },
    zok: { tone: [3, 6], pronunciation: `쩍`, han: `作` },
    cok: { tone: [3], pronunciation: `척`, han: `錯` },
    sok: { tone: [3], pronunciation: `썩`, han: `朔` },
    doe: { tone: [2], pronunciation: `뗘`, han: `朵` },
    toe: { tone: [3, 5], pronunciation: `텨`, han: `唾` },
    goe: { tone: [3], pronunciation: `껴`, han: `鋸` },
    koe: { tone: [4], pronunciation: `켜`, han: `翗` },
    hoe: { tone: [1], pronunciation: `혀`, han: `靴` },
    noeng: { tone: [4], pronunciation: `녕`, han: `娘` },
    loeng: { tone: [2, 4, 5, 6], pronunciation: `령`, han: `量` },
    goeng: { tone: [1, 6], pronunciation: `꼉`, han: `彊` },
    koeng: { tone: [3, 4, 5], pronunciation: `켱`, han: `強` },
    hoeng: { tone: [1, 2, 3], pronunciation: `형`, han: `鄉` },
    zoeng: { tone: [1, 2, 3, 6], pronunciation: `쪙`, han: `象` },
    coeng: { tone: [1, 2, 3, 4], pronunciation: `쳥`, han: `長` },
    soeng: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `쎵`, han: `相` },
    joeng: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `영`, han: `陽` },
    doek: { tone: [3], pronunciation: `뗙`, han: `啄` },
    loek: { tone: [6], pronunciation: `력`, han: `略` },
    goek: { tone: [3], pronunciation: `껵`, han: `腳` },
    koek: { tone: [3, 6], pronunciation: `켝`, han: `卻` },
    zoek: { tone: [3, 6], pronunciation: `쪅`, han: `桌` },
    coek: { tone: [3], pronunciation: `쳑`, han: `卓` },
    soek: { tone: [3], pronunciation: `쎡`, han: `削` },
    joek: { tone: [3, 6], pronunciation: `역`, han: `藥` },
    deoi: { tone: [1, 3, 6], pronunciation: `또이`, han: `對` },
    teoi: { tone: [1, 2, 3, 4], pronunciation: `토이`, han: `推` },
    neoi: { tone: [5, 6], pronunciation: `노이`, han: `女` },
    leoi: { tone: [3, 4, 5, 6], pronunciation: `로이`, han: `類` },
    geoi: { tone: [1, 2, 3, 6], pronunciation: `꼬이`, han: `居` },
    keoi: { tone: [1, 4, 5], pronunciation: `코이`, han: `佉` },
    heoi: { tone: [1, 2, 3, 5], pronunciation: `호이`, han: `許` },
    zeoi: { tone: [1, 2, 3, 6], pronunciation: `쪼이`, han: `追` },
    ceoi: { tone: [1, 2, 3, 4], pronunciation: `초이`, han: `吹` },
    seoi: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `쏘이`, han: `水` },
    jeoi: { tone: [1, 4, 5, 6], pronunciation: `요이`, han: `銳` },
    deon: { tone: [1, 6], pronunciation: `똔`, han: `敦` },
    teon: { tone: [1, 2, 3, 4, 5], pronunciation: `톤`, han: `盾` },
    leon: { tone: [2, 4, 5, 6], pronunciation: `론`, han: `論` },
    zeon: { tone: [1, 2, 3, 6], pronunciation: `쫀`, han: `盡` },
    ceon: { tone: [1, 2, 4], pronunciation: `촌`, han: `巡` },
    seon: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `쏜`, han: `順` },
    jeon: { tone: [6], pronunciation: `욘`, han: `潤` },
    deot: { tone: [1], pronunciation: `뗫`, han: `咄` },
    neot: { tone: [6], pronunciation: `녓`, han: `訥` },
    leot: { tone: [6], pronunciation: `렷`, han: `律` },
    zeot: { tone: [1], pronunciation: `쪗`, han: `卒` },
    ceot: { tone: [1], pronunciation: `쳣`, han: `出` },
    seot: { tone: [1, 6], pronunciation: `쎳`, han: `率` },
    fu: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `f우`, han: `婦` },
    gu: { tone: [1, 2, 3], pronunciation: `꾸`, han: `固` },
    ku: { tone: [1], pronunciation: `쿠`, han: `箍` },
    wu: { tone: [1, 2, 3, 4, 6], pronunciation: `우`, han: `狐` },
    bui: { tone: [1, 3, 6], pronunciation: `뿌이`, han: `貝` },
    pui: { tone: [1, 3, 4, 5], pronunciation: `푸이`, han: `賠` },
    mui: { tone: [4, 5, 6], pronunciation: `무이`, han: `枚` },
    fui: { tone: [1, 2, 3], pronunciation: `f우이`, han: `喙` },
    gui: { tone: [2, 6], pronunciation: `꾸이`, han: `𣪘` },
    kui: { tone: [2, 3], pronunciation: `쿠이`, han: `潰` },
    wui: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `우이`, han: `回` },
    bun: { tone: [1, 2, 3, 6], pronunciation: `뿐`, han: `半` },
    pun: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `푼`, han: `判` },
    mun: { tone: [1, 4, 5, 6], pronunciation: `문`, han: `滿` },
    fun: { tone: [1, 2], pronunciation: `f운`, han: `歡` },
    gun: { tone: [1, 2, 3], pronunciation: `꾼`, han: `觀` },
    wun: { tone: [1, 2, 4, 5, 6], pronunciation: `운`, han: `逭` },
    cun: { tone: [3], pronunciation: `춘`, han: `籿` },
    ung: { tone: [2, 3], pronunciation: `옹`, han: `甕` },
    bung: { tone: [2, 6], pronunciation: `뽕`, han: `菶` },
    pung: { tone: [1, 2, 3, 4], pronunciation: `퐁`, han: `碰` },
    mung: { tone: [1, 2, 4, 5, 6], pronunciation: `몽`, han: `蒙` },
    fung: { tone: [1, 2, 3, 4, 6], pronunciation: `f옹`, han: `風` },
    dung: { tone: [1, 2, 3, 6], pronunciation: `똥`, han: `動` },
    tung: { tone: [1, 2, 3, 4], pronunciation: `통`, han: `通` },
    nung: { tone: [4, 5], pronunciation: `농`, han: `農` },
    lung: { tone: [1, 4, 5, 6], pronunciation: `롱`, han: `弄` },
    gung: { tone: [1, 2, 3, 6], pronunciation: `꽁`, han: `宮` },
    kung: { tone: [4], pronunciation: `콩`, han: `窮` },
    ngung: { tone: [1, 3], pronunciation: `으옹`, han: `壅` },
    hung: { tone: [1, 2, 3, 4, 6], pronunciation: `홍`, han: `雄` },
    zung: { tone: [1, 2, 3, 6], pronunciation: `쫑`, han: `中` },
    cung: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `총`, han: `充` },
    sung: { tone: [1, 2, 3, 4], pronunciation: `쏭`, han: `送` },
    jung: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `용`, han: `用` },
    but: { tone: [3, 6], pronunciation: `뽓`, han: `勃` },
    put: { tone: [3], pronunciation: `폿`, han: `潑` },
    mut: { tone: [3, 6], pronunciation: `못`, han: `沒` },
    fut: { tone: [3], pronunciation: `f옷`, han: `闊` },
    kut: { tone: [3], pronunciation: `콧`, han: `括` },
    wut: { tone: [6], pronunciation: `옷`, han: `活` },
    uk: { tone: [1], pronunciation: `옥`, han: `屋` },
    buk: { tone: [1, 6], pronunciation: `뽁`, han: `卜` },
    puk: { tone: [1], pronunciation: `폭`, han: `仆` },
    muk: { tone: [6], pronunciation: `목`, han: `目` },
    fuk: { tone: [1, 6], pronunciation: `f옥`, han: `服` },
    duk: { tone: [1, 6], pronunciation: `똑`, han: `獨` },
    tuk: { tone: [1], pronunciation: `톡`, han: `禿` },
    nuk: { tone: [6], pronunciation: `녹`, han: `恧` },
    luk: { tone: [1, 6], pronunciation: `록`, han: `六` },
    guk: { tone: [1, 6], pronunciation: `꼭`, han: `局` },
    kuk: { tone: [1], pronunciation: `콕`, han: `曲` },
    nguk: { tone: [1], pronunciation: `으옥`, han: `剭` },
    huk: { tone: [1, 6], pronunciation: `혹`, han: `哭` },
    zuk: { tone: [1, 3, 6], pronunciation: `쪽`, han: `觸` },
    cuk: { tone: [1, 3], pronunciation: `촉`, han: `束` },
    suk: { tone: [1, 3, 6], pronunciation: `쏙`, han: `宿` },
    juk: { tone: [1, 6], pronunciation: `욕`, han: `欲` },
    zyu: { tone: [1, 2, 3, 6], pronunciation: `쮜`, han: `主` },
    cyu: { tone: [1, 2, 3, 4, 5], pronunciation: `취`, han: `處` },
    syu: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `쒸`, han: `庶` },
    jyu: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `위`, han: `語` },
    dyun: { tone: [1, 2, 3, 6], pronunciation: `뛴`, han: `端` },
    tyun: { tone: [1, 4, 5], pronunciation: `튄`, han: `團` },
    nyun: { tone: [5, 6], pronunciation: `뉜`, han: `暖` },
    lyun: { tone: [1, 2, 4, 5, 6], pronunciation: `륀`, han: `亂` },
    gyun: { tone: [1, 2, 3, 6], pronunciation: `뀐`, han: `捐` },
    kyun: { tone: [4], pronunciation: `퀸`, han: `拳` },
    hyun: { tone: [1, 2, 3], pronunciation: `휜`, han: `犬` },
    zyun: { tone: [2, 3, 6], pronunciation: `쮠`, han: `轉` },
    cyun: { tone: [1, 2, 3, 4, 5], pronunciation: `췬`, han: `存` },
    syun: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `쒼`, han: `算` },
    jyun: { tone: [1, 2, 3, 4, 5, 6], pronunciation: `윈`, han: `願` },
    dyut: { tone: [6], pronunciation: `뜃`, han: `奪` },
    tyut: { tone: [3], pronunciation: `튓`, han: `脫` },
    lyut: { tone: [3, 6], pronunciation: `륏`, han: `劣` },
    gyut: { tone: [3, 6], pronunciation: `뀟`, han: `橛` },
    kyut: { tone: [3], pronunciation: `큇`, han: `缺` },
    hyut: { tone: [3], pronunciation: `휫`, han: `血` },
    zyut: { tone: [3, 6], pronunciation: `쮯`, han: `絕` },
    cyut: { tone: [3], pronunciation: `췻`, han: `撮` },
    syut: { tone: [3], pronunciation: `쓋`, han: `雪` },
    jyut: { tone: [3, 6], pronunciation: `윗`, han: `月` },
    m: { tone: [2, 4, 6], pronunciation: `음`, han: `呣` },
    hm: { tone: [1], pronunciation: `흠`, han: `噷` },
    ng: { tone: [2, 4, 5, 6], pronunciation: `은/응`, han: `誤` },
    hng: { tone: [6], pronunciation: `흥`, han: `哼` },
  },
};

export default syllable;
