export default function Syllable() {
  return (
    <div className="w-full mt-8 text-center">
      <div className="flex justify-between">
        <div>성모(聲母)</div>
        <div>운모(韻母)</div>
        <div>성조(聲調)</div>
      </div>
      <table className="mx-auto border">
        <tr>
          <td className="border w-6">　</td>
          <td className="border w-6 text-pink-600">-</td>
          <td className="border w-6 text-pink-600">b</td>
          <td className="border w-6 text-pink-600">p</td>
          <td className="border w-6 text-pink-600">m</td>
          <td className="border w-6 text-pink-600">f</td>
          <td className="border w-6 text-pink-600">d</td>
          <td className="border w-6 text-pink-600">t</td>
          <td className="border w-6 text-pink-600">n</td>
          <td className="border w-6 text-pink-600">l</td>
          <td className="border w-6 text-pink-600">g</td>
          <td className="border w-6 text-pink-600">k</td>
          <td className="border w-6 text-pink-600">ng</td>
          <td className="border w-6 text-pink-600">h</td>
          <td className="border w-6 text-pink-600">gw</td>
          <td className="border w-6 text-pink-600">kw</td>
          <td className="border w-6 text-pink-600">w</td>
          <td className="border w-6 text-pink-600">z</td>
          <td className="border w-6 text-pink-600">c</td>
          <td className="border w-6 text-pink-600">s</td>
          <td className="border w-6 text-pink-600">j</td>
        </tr>

        <tr>
          <td className="border text-blue-600">aa</td>
          <td className="border">啊</td>
          <td className="border">巴</td>
          <td className="border">扒</td>
          <td className="border">媽</td>
          <td className="border">花</td>
          <td className="border">打</td>
          <td className="border">他</td>
          <td className="border">拿</td>
          <td className="border">啦</td>
          <td className="border">家</td>
          <td className="border">卡</td>
          <td className="border">牙</td>
          <td className="border">下</td>
          <td className="border">掛</td>
          <td className="border">誇</td>
          <td className="border">華</td>
          <td className="border">渣</td>
          <td className="border">查</td>
          <td className="border">沙</td>
          <td className="border">也</td>
        </tr>
        <tr>
          <td className="border text-blue-600">aai</td>
          <td className="border">挨</td>
          <td className="border">拜</td>
          <td className="border">排</td>
          <td className="border">埋</td>
          <td className="border">快</td>
          <td className="border">帶</td>
          <td className="border">太</td>
          <td className="border">嬭</td>
          <td className="border">拉</td>
          <td className="border">戒</td>
          <td className="border">楷</td>
          <td className="border">睚</td>
          <td className="border">鞋</td>
          <td className="border">罫</td>
          <td className="border">嘳</td>
          <td className="border">懷</td>
          <td className="border">齋</td>
          <td className="border">柴</td>
          <td className="border">曬</td>
          <td className="border">踹</td>
        </tr>
        <tr>
          <td className="border text-blue-600">aau</td>
          <td className="border">拗</td>
          <td className="border">苞</td>
          <td className="border">拋</td>
          <td className="border">卯</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">鬧</td>
          <td className="border">撈</td>
          <td className="border">教</td>
          <td className="border">靠</td>
          <td className="border">爻</td>
          <td className="border">巧</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">爪</td>
          <td className="border">巢</td>
          <td className="border">筲</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">aam</td>
          <td className="border">菡</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">擔</td>
          <td className="border">探</td>
          <td className="border">男</td>
          <td className="border">攬</td>
          <td className="border">監</td>
          <td className="border">　</td>
          <td className="border">啽</td>
          <td className="border">咸</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">簪</td>
          <td className="border">慘</td>
          <td className="border">三</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">aan</td>
          <td className="border">晏</td>
          <td className="border">班</td>
          <td className="border">攀</td>
          <td className="border">晚</td>
          <td className="border">繁</td>
          <td className="border">單</td>
          <td className="border">檀</td>
          <td className="border">難</td>
          <td className="border">讕</td>
          <td className="border">艱</td>
          <td className="border">　</td>
          <td className="border">眼</td>
          <td className="border">閒</td>
          <td className="border">關</td>
          <td className="border">　</td>
          <td className="border">還</td>
          <td className="border">讚</td>
          <td className="border">殘</td>
          <td className="border">山</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">aang</td>
          <td className="border">罌</td>
          <td className="border">唪</td>
          <td className="border">鵬</td>
          <td className="border">猛</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">冷</td>
          <td className="border">更</td>
          <td className="border">　</td>
          <td className="border">硬</td>
          <td className="border">夯</td>
          <td className="border">逛</td>
          <td className="border">眶</td>
          <td className="border">橫</td>
          <td className="border">諍</td>
          <td className="border">撐</td>
          <td className="border">生</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">aap</td>
          <td className="border">鴨</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">答</td>
          <td className="border">塌</td>
          <td className="border">納</td>
          <td className="border">臘</td>
          <td className="border">甲</td>
          <td className="border">　</td>
          <td className="border">押</td>
          <td className="border">狹</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">集</td>
          <td className="border">插</td>
          <td className="border">翣</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">aat</td>
          <td className="border">壓</td>
          <td className="border">扒</td>
          <td className="border">　</td>
          <td className="border">抹</td>
          <td className="border">發</td>
          <td className="border">達</td>
          <td className="border">躂</td>
          <td className="border">捺</td>
          <td className="border">辣</td>
          <td className="border">戛</td>
          <td className="border">卡</td>
          <td className="border">扤</td>
          <td className="border">　</td>
          <td className="border">刮</td>
          <td className="border">　</td>
          <td className="border">滑</td>
          <td className="border">扎</td>
          <td className="border">察</td>
          <td className="border">殺</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">aak</td>
          <td className="border">軛</td>
          <td className="border">帛</td>
          <td className="border">拍</td>
          <td className="border">擘</td>
          <td className="border">謋</td>
          <td className="border">咑</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">勒</td>
          <td className="border">革</td>
          <td className="border">緙</td>
          <td className="border">額</td>
          <td className="border">客</td>
          <td className="border">摑</td>
          <td className="border">　</td>
          <td className="border">畫</td>
          <td className="border">澤</td>
          <td className="border">賊</td>
          <td className="border">索</td>
          <td className="border">喫</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ai</td>
          <td className="border">矮</td>
          <td className="border">閉</td>
          <td className="border">批</td>
          <td className="border">迷</td>
          <td className="border">費</td>
          <td className="border">弟</td>
          <td className="border">體</td>
          <td className="border">泥</td>
          <td className="border">禮</td>
          <td className="border">雞</td>
          <td className="border">啟</td>
          <td className="border">危</td>
          <td className="border">兮</td>
          <td className="border">歸</td>
          <td className="border">規</td>
          <td className="border">遺</td>
          <td className="border">祭</td>
          <td className="border">齊</td>
          <td className="border">勢</td>
          <td className="border">曳</td>
        </tr>
        <tr>
          <td className="border text-blue-600">au</td>
          <td className="border">漚</td>
          <td className="border">堷</td>
          <td className="border">剖</td>
          <td className="border">侔</td>
          <td className="border">否</td>
          <td className="border">鬥</td>
          <td className="border">頭</td>
          <td className="border">耨</td>
          <td className="border">漏</td>
          <td className="border">救</td>
          <td className="border">求</td>
          <td className="border">偶</td>
          <td className="border">後</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">走</td>
          <td className="border">醜</td>
          <td className="border">受</td>
          <td className="border">褎</td>
        </tr>
        <tr>
          <td className="border text-blue-600">am</td>
          <td className="border">暗</td>
          <td className="border">泵</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">抌</td>
          <td className="border">氹</td>
          <td className="border">稔</td>
          <td className="border">林</td>
          <td className="border">金</td>
          <td className="border">琴</td>
          <td className="border">韽</td>
          <td className="border">含</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">寖</td>
          <td className="border">侵</td>
          <td className="border">心</td>
          <td className="border">淫</td>
        </tr>
        <tr>
          <td className="border text-blue-600">an</td>
          <td className="border">　</td>
          <td className="border">品</td>
          <td className="border">噴</td>
          <td className="border">問</td>
          <td className="border">分</td>
          <td className="border">躉</td>
          <td className="border">吞</td>
          <td className="border">捻</td>
          <td className="border">　</td>
          <td className="border">根</td>
          <td className="border">芹</td>
          <td className="border">銀</td>
          <td className="border">恨</td>
          <td className="border">軍</td>
          <td className="border">困</td>
          <td className="border">溫</td>
          <td className="border">震</td>
          <td className="border">陳</td>
          <td className="border">神</td>
          <td className="border">引</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ang</td>
          <td className="border">鶯</td>
          <td className="border">崩</td>
          <td className="border">堋</td>
          <td className="border">盟</td>
          <td className="border">揈</td>
          <td className="border">等</td>
          <td className="border">騰</td>
          <td className="border">能</td>
          <td className="border">舲</td>
          <td className="border">庚</td>
          <td className="border">掯</td>
          <td className="border">罃</td>
          <td className="border">幸</td>
          <td className="border">觥</td>
          <td className="border">　</td>
          <td className="border">宏</td>
          <td className="border">爭</td>
          <td className="border">層</td>
          <td className="border">蹭</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ap</td>
          <td className="border">洽</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">耷</td>
          <td className="border">　</td>
          <td className="border">粒</td>
          <td className="border">立</td>
          <td className="border">急</td>
          <td className="border">吸</td>
          <td className="border">岋</td>
          <td className="border">合</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">執</td>
          <td className="border">輯</td>
          <td className="border">拾</td>
          <td className="border">潝</td>
        </tr>
        <tr>
          <td className="border text-blue-600">at</td>
          <td className="border">　</td>
          <td className="border">筆</td>
          <td className="border">匹</td>
          <td className="border">密</td>
          <td className="border">紼</td>
          <td className="border">突</td>
          <td className="border">　</td>
          <td className="border">吶</td>
          <td className="border">甩</td>
          <td className="border">吉</td>
          <td className="border">咳</td>
          <td className="border">兀</td>
          <td className="border">瞎</td>
          <td className="border">骨</td>
          <td className="border">　</td>
          <td className="border">屈</td>
          <td className="border">質</td>
          <td className="border">七</td>
          <td className="border">實</td>
          <td className="border">日</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ak</td>
          <td className="border">偓</td>
          <td className="border">北</td>
          <td className="border">　</td>
          <td className="border">默</td>
          <td className="border">　</td>
          <td className="border">得</td>
          <td className="border">　</td>
          <td className="border">疒</td>
          <td className="border">勒</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">呃</td>
          <td className="border">黑</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">側</td>
          <td className="border">測</td>
          <td className="border">塞</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">e</td>
          <td className="border">誒</td>
          <td className="border">啤</td>
          <td className="border">　</td>
          <td className="border">乜</td>
          <td className="border">啡</td>
          <td className="border">爹</td>
          <td className="border">　</td>
          <td className="border">呢</td>
          <td className="border">咧</td>
          <td className="border">痂</td>
          <td className="border">伽</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">謝</td>
          <td className="border">邪</td>
          <td className="border">射</td>
          <td className="border">夜</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ei</td>
          <td className="border">欸</td>
          <td className="border">悲</td>
          <td className="border">披</td>
          <td className="border">微</td>
          <td className="border">飛</td>
          <td className="border">地</td>
          <td className="border">　</td>
          <td className="border">珥</td>
          <td className="border">理</td>
          <td className="border">機</td>
          <td className="border">奇</td>
          <td className="border">　</td>
          <td className="border">起</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">死</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">eu</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">調</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">em</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">舐</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">eng</td>
          <td className="border">　</td>
          <td className="border">餅</td>
          <td className="border">平</td>
          <td className="border">名</td>
          <td className="border">　</td>
          <td className="border">掟</td>
          <td className="border">廳</td>
          <td className="border">　</td>
          <td className="border">靚</td>
          <td className="border">鏡</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">輕</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">鄭</td>
          <td className="border">青</td>
          <td className="border">腥</td>
          <td className="border">贏</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ep</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">夾</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ek</td>
          <td className="border">　</td>
          <td className="border">壁</td>
          <td className="border">劈</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">笛</td>
          <td className="border">踢</td>
          <td className="border">　</td>
          <td className="border">叻</td>
          <td className="border">　</td>
          <td className="border">劇</td>
          <td className="border">　</td>
          <td className="border">吃</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">炙</td>
          <td className="border">尺</td>
          <td className="border">石</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">i</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">眯</td>
          <td className="border">　</td>
          <td className="border">啲</td>
          <td className="border">　</td>
          <td className="border">呢</td>
          <td className="border">唎</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">緇</td>
          <td className="border">詞</td>
          <td className="border">試</td>
          <td className="border">意</td>
        </tr>
        <tr>
          <td className="border text-blue-600">iu</td>
          <td className="border">　</td>
          <td className="border">表</td>
          <td className="border">漂</td>
          <td className="border">妙</td>
          <td className="border">覅</td>
          <td className="border">調</td>
          <td className="border">調</td>
          <td className="border">鳥</td>
          <td className="border">了</td>
          <td className="border">嬌</td>
          <td className="border">橋</td>
          <td className="border">　</td>
          <td className="border">枵</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">焦</td>
          <td className="border">昭</td>
          <td className="border">消</td>
          <td className="border">搖</td>
        </tr>
        <tr>
          <td className="border text-blue-600">im</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">點</td>
          <td className="border">添</td>
          <td className="border">念</td>
          <td className="border">斂</td>
          <td className="border">劍</td>
          <td className="border">黔</td>
          <td className="border">　</td>
          <td className="border">欠</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">沾</td>
          <td className="border">潛</td>
          <td className="border">禪</td>
          <td className="border">厭</td>
        </tr>
        <tr>
          <td className="border text-blue-600">in</td>
          <td className="border">　</td>
          <td className="border">辯</td>
          <td className="border">偏</td>
          <td className="border">面</td>
          <td className="border">　</td>
          <td className="border">典</td>
          <td className="border">天</td>
          <td className="border">年</td>
          <td className="border">連</td>
          <td className="border">堅</td>
          <td className="border">虔</td>
          <td className="border">　</td>
          <td className="border">顯</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">剪</td>
          <td className="border">前</td>
          <td className="border">先</td>
          <td className="border">延</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ing</td>
          <td className="border">　</td>
          <td className="border">冰</td>
          <td className="border">瓶</td>
          <td className="border">明</td>
          <td className="border">　</td>
          <td className="border">訂</td>
          <td className="border">挺</td>
          <td className="border">寧</td>
          <td className="border">領</td>
          <td className="border">經</td>
          <td className="border">傾</td>
          <td className="border">　</td>
          <td className="border">輕</td>
          <td className="border">炯</td>
          <td className="border">　</td>
          <td className="border">永</td>
          <td className="border">晶</td>
          <td className="border">呈</td>
          <td className="border">星</td>
          <td className="border">英</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ip</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">碟</td>
          <td className="border">貼</td>
          <td className="border">涅</td>
          <td className="border">獵</td>
          <td className="border">劫</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">協</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">接</td>
          <td className="border">妾</td>
          <td className="border">涉</td>
          <td className="border">業</td>
        </tr>
        <tr>
          <td className="border text-blue-600">it</td>
          <td className="border">　</td>
          <td className="border">必</td>
          <td className="border">撇</td>
          <td className="border">滅</td>
          <td className="border">　</td>
          <td className="border">跌</td>
          <td className="border">鐵</td>
          <td className="border">　</td>
          <td className="border">列</td>
          <td className="border">潔</td>
          <td className="border">揭</td>
          <td className="border">齧</td>
          <td className="border">歇</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">節</td>
          <td className="border">切</td>
          <td className="border">舌</td>
          <td className="border">熱</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ik</td>
          <td className="border">　</td>
          <td className="border">碧</td>
          <td className="border">癖</td>
          <td className="border">覓</td>
          <td className="border">　</td>
          <td className="border">的</td>
          <td className="border">惕</td>
          <td className="border">匿</td>
          <td className="border">力</td>
          <td className="border">極</td>
          <td className="border">棘</td>
          <td className="border">　</td>
          <td className="border">瞁</td>
          <td className="border">馘</td>
          <td className="border">隙</td>
          <td className="border">域</td>
          <td className="border">直</td>
          <td className="border">斥</td>
          <td className="border">食</td>
          <td className="border">亦</td>
        </tr>
        <tr>
          <td className="border text-blue-600">o</td>
          <td className="border">柯</td>
          <td className="border">播</td>
          <td className="border">破</td>
          <td className="border">磨</td>
          <td className="border">火</td>
          <td className="border">多</td>
          <td className="border">妥</td>
          <td className="border">挪</td>
          <td className="border">羅</td>
          <td className="border">哥</td>
          <td className="border">鈳</td>
          <td className="border">我</td>
          <td className="border">可</td>
          <td className="border">過</td>
          <td className="border">　</td>
          <td className="border">禍</td>
          <td className="border">助</td>
          <td className="border">初</td>
          <td className="border">所</td>
          <td className="border">唷</td>
        </tr>
        <tr>
          <td className="border text-blue-600">oi</td>
          <td className="border">靉</td>
          <td className="border">　</td>
          <td className="border">俖</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">代</td>
          <td className="border">胎</td>
          <td className="border">內</td>
          <td className="border">來</td>
          <td className="border">改</td>
          <td className="border">丐</td>
          <td className="border">礙</td>
          <td className="border">海</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">載</td>
          <td className="border">才</td>
          <td className="border">鰓</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ou</td>
          <td className="border">奧</td>
          <td className="border">布</td>
          <td className="border">鋪</td>
          <td className="border">無</td>
          <td className="border">　</td>
          <td className="border">盜</td>
          <td className="border">桃</td>
          <td className="border">腦</td>
          <td className="border">露</td>
          <td className="border">告</td>
          <td className="border">　</td>
          <td className="border">傲</td>
          <td className="border">豪</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">皂</td>
          <td className="border">操</td>
          <td className="border">數</td>
          <td className="border">𢝊</td>
        </tr>
        <tr>
          <td className="border text-blue-600">on</td>
          <td className="border">安</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">干</td>
          <td className="border">　</td>
          <td className="border">岸</td>
          <td className="border">寒</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ong</td>
          <td className="border">骯</td>
          <td className="border">傍</td>
          <td className="border">旁</td>
          <td className="border">網</td>
          <td className="border">防</td>
          <td className="border">當</td>
          <td className="border">堂</td>
          <td className="border">囊</td>
          <td className="border">閬</td>
          <td className="border">降</td>
          <td className="border">抗</td>
          <td className="border">卬</td>
          <td className="border">航</td>
          <td className="border">廣</td>
          <td className="border">曠</td>
          <td className="border">黃</td>
          <td className="border">贓</td>
          <td className="border">藏</td>
          <td className="border">喪</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ot</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">割</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">喝</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ok</td>
          <td className="border">堊</td>
          <td className="border">博</td>
          <td className="border">樸</td>
          <td className="border">莫</td>
          <td className="border">藿</td>
          <td className="border">度</td>
          <td className="border">託</td>
          <td className="border">諾</td>
          <td className="border">落</td>
          <td className="border">覺</td>
          <td className="border">確</td>
          <td className="border">樂</td>
          <td className="border">鶴</td>
          <td className="border">國</td>
          <td className="border">廓</td>
          <td className="border">獲</td>
          <td className="border">作</td>
          <td className="border">錯</td>
          <td className="border">朔</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">oe</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">朵</td>
          <td className="border">唾</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">鋸</td>
          <td className="border">翗</td>
          <td className="border">　</td>
          <td className="border">靴</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">oeng</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">娘</td>
          <td className="border">量</td>
          <td className="border">彊</td>
          <td className="border">強</td>
          <td className="border">　</td>
          <td className="border">鄉</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">象</td>
          <td className="border">長</td>
          <td className="border">相</td>
          <td className="border">陽</td>
        </tr>
        <tr>
          <td className="border text-blue-600">oek</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">啄</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">略</td>
          <td className="border">腳</td>
          <td className="border">卻</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">桌</td>
          <td className="border">卓</td>
          <td className="border">削</td>
          <td className="border">藥</td>
        </tr>
        <tr>
          <td className="border text-blue-600">eoi</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">對</td>
          <td className="border">推</td>
          <td className="border">女</td>
          <td className="border">類</td>
          <td className="border">居</td>
          <td className="border">佉</td>
          <td className="border">　</td>
          <td className="border">許</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">追</td>
          <td className="border">吹</td>
          <td className="border">水</td>
          <td className="border">銳</td>
        </tr>
        <tr>
          <td className="border text-blue-600">eon</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">敦</td>
          <td className="border">盾</td>
          <td className="border">　</td>
          <td className="border">論</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">盡</td>
          <td className="border">巡</td>
          <td className="border">順</td>
          <td className="border">潤</td>
        </tr>
        <tr>
          <td className="border text-blue-600">eot</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">咄</td>
          <td className="border">　</td>
          <td className="border">訥</td>
          <td className="border">律</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">卒</td>
          <td className="border">出</td>
          <td className="border">率</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">u</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">婦</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">固</td>
          <td className="border">箍</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">狐</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ui</td>
          <td className="border">　</td>
          <td className="border">貝</td>
          <td className="border">賠</td>
          <td className="border">枚</td>
          <td className="border">喙</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">𣪘</td>
          <td className="border">潰</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">回</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">un</td>
          <td className="border">　</td>
          <td className="border">半</td>
          <td className="border">判</td>
          <td className="border">滿</td>
          <td className="border">歡</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">觀</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">逭</td>
          <td className="border">　</td>
          <td className="border">籿</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ung</td>
          <td className="border">甕</td>
          <td className="border">菶</td>
          <td className="border">碰</td>
          <td className="border">蒙</td>
          <td className="border">風</td>
          <td className="border">動</td>
          <td className="border">通</td>
          <td className="border">農</td>
          <td className="border">弄</td>
          <td className="border">宮</td>
          <td className="border">窮</td>
          <td className="border">壅</td>
          <td className="border">雄</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">中</td>
          <td className="border">充</td>
          <td className="border">送</td>
          <td className="border">用</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ut</td>
          <td className="border">　</td>
          <td className="border">勃</td>
          <td className="border">潑</td>
          <td className="border">沒</td>
          <td className="border">闊</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">括</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">活</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">uk</td>
          <td className="border">屋</td>
          <td className="border">卜</td>
          <td className="border">仆</td>
          <td className="border">目</td>
          <td className="border">服</td>
          <td className="border">獨</td>
          <td className="border">禿</td>
          <td className="border">恧</td>
          <td className="border">六</td>
          <td className="border">局</td>
          <td className="border">曲</td>
          <td className="border">剭</td>
          <td className="border">哭</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">觸</td>
          <td className="border">束</td>
          <td className="border">宿</td>
          <td className="border">欲</td>
        </tr>
        <tr>
          <td className="border text-blue-600">yu</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">主</td>
          <td className="border">處</td>
          <td className="border">庶</td>
          <td className="border">語</td>
        </tr>
        <tr>
          <td className="border text-blue-600">yun</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">端</td>
          <td className="border">團</td>
          <td className="border">暖</td>
          <td className="border">亂</td>
          <td className="border">捐</td>
          <td className="border">拳</td>
          <td className="border">　</td>
          <td className="border">犬</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">轉</td>
          <td className="border">存</td>
          <td className="border">算</td>
          <td className="border">願</td>
        </tr>
        <tr>
          <td className="border text-blue-600">yut</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">奪</td>
          <td className="border">脫</td>
          <td className="border">　</td>
          <td className="border">劣</td>
          <td className="border">橛</td>
          <td className="border">缺</td>
          <td className="border">　</td>
          <td className="border">血</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">絕</td>
          <td className="border">撮</td>
          <td className="border">雪</td>
          <td className="border">月</td>
        </tr>
        <tr>
          <td className="border text-blue-600">m</td>
          <td className="border">呣</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">噷</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
        <tr>
          <td className="border text-blue-600">ng</td>
          <td className="border">誤</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">哼</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
          <td className="border">　</td>
        </tr>
      </table>
    </div>
  );
}
